In [1]:
%cd /content/drive/MyDrive/second_paper_insha_allah/data

/content/drive/MyDrive/second_paper_insha_allah/data

In [2]:
from scipy.stats import kendalltau
import pandas as pd
from scipy.stats import pearsonr
from tqdm import tqdm
tqdm.pandas()

In [3]:
annotations_raw = pd.read_excel("sample_annotators_data_fin_avg.xlsx")
annotations_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Human_annotation_exp    203 non-null    int64
 1   Human_annotation_exp.1  203 non-null    int64
 2   Human_annotation_exp.2  203 non-null    int64
 3   Human_annotation_exp.3  203 non-null    int64
dtypes: int64(4)
memory usage: 6.5 KB

In [4]:
def exctract_score(ann):
  score = None
  scores = ann.split('\n')[-3:]
  try:
    error_det_score = int(scores[0].split(':')[-1].strip())
  except:
    print(ann)

  error_corr_score = int(scores[1].split(':')[-1].strip())
  src_score = int(scores[2].split(':')[-1].strip())
  return round((error_det_score + error_corr_score + round(src_score*(2/3)))*(5/6))

In [ ]:
# ann_model_0 = annotations_raw['Human_annotation_exp'].progress_apply(exctract_score)
# ann_model_1 = annotations_raw['Human_annotation_exp.1'].progress_apply(exctract_score)
# ann_model_2 = annotations_raw['Human_annotation_exp.2'].progress_apply(exctract_score)
# ann_model_3 = annotations_raw['Human_annotation_exp.3'].progress_apply(exctract_score)

In [5]:
ann_model_0 = annotations_raw['Human_annotation_exp']#.progress_apply(exctract_score)
ann_model_1 = annotations_raw['Human_annotation_exp.1']#.progress_apply(exctract_score)
ann_model_2 = annotations_raw['Human_annotation_exp.2']#.progress_apply(exctract_score)
ann_model_3 = annotations_raw['Human_annotation_exp.3']#.progress_apply(exctract_score)

In [6]:
data = pd.read_excel('/content/drive/MyDrive/second_paper_insha_allah/data/sample_data_fin_evals_exp5.xlsx')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 41 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   claim                                     203 non-null    object
 1   evidence                                  203 non-null    object
 2   label                                     203 non-null    object
 3   metadata                                  203 non-null    object
 4   explanation                               203 non-null    object
 5   mistral_exp                               203 non-null    object
 6   llama_exp                                 203 non-null    object
 7   gpt-4_exp                                 203 non-null    object
 8   geval_eval                                203 non-null    object
 9   geval_eval_with_links                     203 non-null    object
 10  prom_eval                                 203 non-null    object
 11  prom_eval_with_links                      203 non-null    object
 12  FinGrAct_eval                             203 non-null    object
 13  FinGrAct_eval_with_links                  203 non-null    object
 14  prom_eval_exp                             203 non-null    object
 15  prom_eval_mist_exp                        203 non-null    object
 16  prom_eval_llama_exp                       203 non-null    object
 17  prom_eval_gpt_exp                         203 non-null    object
 18  FinGrAct_fact_check_res                   203 non-null    object
 19  FinGrAct_align_exp                        203 non-null    object
 20  FinGrAct_align_mistral_exp                203 non-null    object
 21  FinGrAct_align_llama_exp                  203 non-null    object
 22  FinGrAct_align_gpt_exp                    203 non-null    object
 23  FinGrAct_detailed_eval                    203 non-null    object
 24  links_detected_exp                        87 non-null     object
 25  links_detected_mistral                    51 non-null     object
 26  links_detected_llama                      58 non-null     object
 27  links_detected_gpt                        56 non-null     object
 28  url_content_exp                           87 non-null     object
 29  url_content_mistral                       51 non-null     object
 30  url_content_llama                         58 non-null     object
 31  url_content_gpt                           56 non-null     object
 32  FinGrAct_align_exp_with_links             203 non-null    object
 33  FinGrAct_align_mistral_exp_with_links     203 non-null    object
 34  FinGrAct_align_llama_exp_with_links       203 non-null    object
 35  FinGrAct_align_gpt_exp_with_links         203 non-null    object
 36  FinGrAct_detailed_eval_with_links         203 non-null    object
 37  prom_feedback_exp_with_links              203 non-null    object
 38  prom_feedback_exp_mistral_exp_with_links  203 non-null    object
 39  prom_feedback_exp_llama_exp_with_links    203 non-null    object
 40  prom_feedback_exp_gpt_exp_with_links      203 non-null    object
dtypes: object(41)
memory usage: 65.2+ KB

In [7]:
def get_score_list(score_list):
  model0, model1, model2, model3 = [], [], [], []
  #print(score_list)
  for item in score_list:
    model0.append(int(float(item[0])))
    model1.append(int(float(item[1])))
    model2.append(int(float(item[2])))
    model3.append(int(float(item[3])))
  return model0, model1, model2, model3

In [8]:
def format_input(input):
  return [int(float(item)) for item in input.replace('[', '').replace(']', '').split(',')]

In [ ]:
# data.geval_eval = data.geval_eval.apply(format_input)
# data.prom_eval = data.prom_eval.apply(format_input)
# data.FinGrAct_eval = data.FinGrAct_eval.apply(format_input)

In [9]:
data.FinGrAct_eval

0      [5, 5, 5, 5]
1      [2, 3, 5, 3]
2      [3, 3, 3, 3]
3      [3, 3, 3, 2]
4      [0, 3, 3, 3]
           ...
198    [3, 3, 3, 3]
199    [5, 3, 3, 3]
200    [3, 3, 3, 3]
201    [5, 3, 3, 3]
202    [2, 2, 2, 0]
Name: FinGrAct_eval, Length: 203, dtype: object

In [11]:
geval_score_exp_0, geval_score_exp_1, geval_score_exp_2, geval_score_exp_3 = get_score_list(data.geval_eval.apply(format_input).to_list())
prom_score_exp_0, prom_score_exp_1, prom_score_exp_2, prom_score_exp_3 = get_score_list(data.prom_eval.apply(format_input).to_list())
FinGrAct_score_exp_0, FinGrAct_score_exp_1, FinGrAct_score_exp_2, FinGrAct_score_exp_3 = get_score_list(data.FinGrAct_eval.apply(format_input).to_list())

In [13]:
# data.geval_eval_with_links = data.geval_eval_with_links.apply(format_input)
# data.prom_eval_with_links = data.prom_eval_with_links.apply(format_input)
# data.FinGrAct_eval_with_links = data.FinGrAct_eval_with_links.apply(format_input)

In [12]:
geval_score_exp_with_lnk_0, geval_score_exp_with_lnk_1, geval_score_exp_with_lnk_2, geval_score_exp_with_lnk_3 = get_score_list(data.geval_eval_with_links.apply(format_input).to_list())
prom_score_exp_with_lnk_0, prom_score_exp_with_lnk_1, prom_score_exp_with_lnk_2, prom_score_exp_with_lnk_3 = get_score_list(data.prom_eval_with_links.apply(format_input).to_list())
FinGrAct_score_exp_with_lnk_0, FinGrAct_score_exp_with_lnk_1, FinGrAct_score_exp_with_lnk_2, FinGrAct_score_exp_with_lnk_3 = get_score_list(data.FinGrAct_eval_with_links.apply(format_input).to_list())

In [14]:
data.prom_eval_with_links.head(20)

0     [3, 5, 4, 5]
1     [2, 2, 3, 3]
2     [3, 3, 4, 3]
3     [1, 3, 3, 3]
4     [1, 3, 2, 4]
5     [1, 3, 3, 2]
6     [1, 3, 4, 3]
7     [1, 2, 3, 3]
8     [1, 3, 4, 3]
9     [2, 3, 3, 5]
10    [1, 2, 2, 3]
11    [4, 4, 2, 3]
12    [3, 3, 2, 2]
13    [1, 2, 2, 2]
14    [2, 4, 3, 2]
15    [1, 3, 2, 4]
16    [1, 3, 3, 3]
17    [2, 3, 3, 3]
18    [2, 3, 2, 3]
19    [1, 3, 2, 2]
Name: prom_eval_with_links, dtype: object

In [15]:
df_score_exp_0 = pd.DataFrame(columns=['ann_model_0', 'geval_score_exp_0', 'prom_score_exp_0', 'FinGrAct_score_exp_0',
                           'geval_score_exp_with_lnk_0', 'prom_score_exp_with_lnk_0', 'FinGrAct_score_exp_with_lnk_0'])
df_score_exp_1 = pd.DataFrame(columns=['ann_model_1', 'geval_score_exp_1', 'prom_score_exp_1', 'FinGrAct_score_exp_1',
                           'geval_score_exp_with_lnk_1', 'prom_score_exp_with_lnk_1', 'FinGrAct_score_exp_with_lnk_1'])
df_score_exp_2 = pd.DataFrame(columns=['ann_model_2', 'geval_score_exp_2', 'prom_score_exp_2', 'FinGrAct_score_exp_2',
                           'geval_score_exp_with_lnk_2', 'prom_score_exp_with_lnk_2', 'FinGrAct_score_exp_with_lnk_2'])
df_score_exp_3 = pd.DataFrame(columns=['ann_model_3', 'geval_score_exp_3', 'prom_score_exp_3', 'FinGrAct_score_exp_3',
                           'geval_score_exp_with_lnk_3', 'prom_score_exp_with_lnk_3', 'FinGrAct_score_exp_with_lnk_3'])

# for explanations of original dataset

In [16]:
df_score_exp_0['ann_model_0'] = ann_model_0
df_score_exp_0['geval_score_exp_0'] = geval_score_exp_0
df_score_exp_0['prom_score_exp_0'] = prom_score_exp_0
df_score_exp_0['FinGrAct_score_exp_0'] = FinGrAct_score_exp_0
df_score_exp_0['geval_score_exp_with_lnk_0'] = geval_score_exp_with_lnk_0
df_score_exp_0['prom_score_exp_with_lnk_0'] = prom_score_exp_with_lnk_0
df_score_exp_0['FinGrAct_score_exp_with_lnk_0'] = FinGrAct_score_exp_with_lnk_0
df_score_exp_0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   ann_model_0                    203 non-null    int64
 1   geval_score_exp_0              203 non-null    int64
 2   prom_score_exp_0               203 non-null    int64
 3   FinGrAct_score_exp_0           203 non-null    int64
 4   geval_score_exp_with_lnk_0     203 non-null    int64
 5   prom_score_exp_with_lnk_0      203 non-null    int64
 6   FinGrAct_score_exp_with_lnk_0  203 non-null    int64
dtypes: int64(7)
memory usage: 11.2 KB

In [17]:
df_score_exp_0[['ann_model_0', 'FinGrAct_score_exp_0','FinGrAct_score_exp_with_lnk_0']][abs(df_score_exp_0.ann_model_0 - df_score_exp_0.FinGrAct_score_exp_0)<abs(df_score_exp_0.ann_model_0 - df_score_exp_0.FinGrAct_score_exp_with_lnk_0)]

     ann_model_0  FinGrAct_score_exp_0  FinGrAct_score_exp_with_lnk_0
128            2                     2                              3
131            3                     3                              2
145            2                     2                              3
151            3                     3                              4
158            2                     3                              5
166            3                     3                              5
168            2                     2                              3
169            2                     2                              1
170            2                     3                              0
173            2                     3                              4
186            3                     3                              5
189            2                     3                              5
191            2                     3                              5
198            2                     3                              4
200            2                     3                              5
202            2                     2                              1

In [18]:
df_score_exp_0[['ann_model_0', 'prom_score_exp_0','prom_score_exp_with_lnk_0']][abs(df_score_exp_0.ann_model_0 - df_score_exp_0.prom_score_exp_0)<abs(df_score_exp_0.ann_model_0 - df_score_exp_0.prom_score_exp_with_lnk_0)]

     ann_model_0  prom_score_exp_0  prom_score_exp_with_lnk_0
8              2                 2                          1
10             2                 2                          1
12             2                 2                          3
14             1                 1                          2
30             2                 2                          1
31             2                 2                          3
32             1                 1                          2
35             1                 1                          2
36             1                 1                          2
43             1                 1                          2
52             2                 2                          1
54             2                 2                          1
56             1                 1                          2
60             1                 2                          3
64             3                 2                          1
65             3                 2                          1
67             2                 2                          1
70             2                 2                          1
75             2                 2                          1
76             3                 3                          1
78             3                 2                          1
87             3                 2                          1
95             2                 2                          3
117            5                 4                          2
124            5                 4                          3
128            2                 2                          1
129            5                 5                          4
130            2                 2                          1
131            3                 4                          1
132            3                 2                          1
134            2                 2                          1
136            5                 3                          2
139            5                 5                          3
147            3                 2                          5
150            3                 3                          5
163            3                 3                          4
168            2                 2                          1
178            3                 4                          5
179            3                 3                          1
183            2                 3                          4
186            3                 3                          2
192            2                 2                          3
196            2                 4                          5
197            2                 4                          5
202            2                 2                          5

In [19]:
df_score_exp_0.corr()

,ann_model_0,geval_score_exp_0,prom_score_exp_0,FinGrAct_score_exp_0,geval_score_exp_with_lnk_0,prom_score_exp_with_lnk_0,FinGrAct_score_exp_with_lnk_0
ann_model_0,1.000000,0.147222,0.328759,0.460242,0.213704,0.404923,0.520632
geval_score_exp_0,0.147222,1.000000,0.050741,0.090329,0.550899,-0.064595,0.064296
prom_score_exp_0,0.328759,0.050741,1.000000,0.459020,0.267561,0.523135,0.375857
FinGrAct_score_exp_0,0.460242,0.090329,0.459020,1.000000,0.295180,0.429116,0.748244
geval_score_exp_with_lnk_0,0.213704,0.550899,0.267561,0.295180,1.000000,0.261228,0.323826
prom_score_exp_with_lnk_0,0.404923,-0.064595,0.523135,0.429116,0.261228,1.000000,0.347286
FinGrAct_score_exp_with_lnk_0,0.520632,0.064296,0.375857,0.748244,0.323826,0.347286,1.000000

In [22]:
from scipy.stats.stats import pearsonr
print(pearsonr(df_score_exp_0.ann_model_0.to_list(), df_score_exp_0.geval_score_exp_0.to_list()))
print(pearsonr(df_score_exp_0.ann_model_0.to_list(), df_score_exp_0.prom_score_exp_0.to_list()))
print(pearsonr(df_score_exp_0.ann_model_0.to_list(), df_score_exp_0.FinGrAct_score_exp_0.to_list()))
print(pearsonr(df_score_exp_0.ann_model_0.to_list(), df_score_exp_0.geval_score_exp_with_lnk_0.to_list()))
print(pearsonr(df_score_exp_0.ann_model_0.to_list(), df_score_exp_0.prom_score_exp_with_lnk_0.to_list()))
print(pearsonr(df_score_exp_0.ann_model_0.to_list(), df_score_exp_0.FinGrAct_score_exp_with_lnk_0.to_list()))

PearsonRResult(statistic=0.14722191493088496, pvalue=0.03607584404842176)
PearsonRResult(statistic=0.3287593509212861, pvalue=1.6764400267987318e-06)
PearsonRResult(statistic=0.46024171202420944, pvalue=4.896733829810648e-12)
PearsonRResult(statistic=0.21370413806039326, pvalue=0.002202612521316319)
PearsonRResult(statistic=0.40492278307919116, pvalue=2.0692761202955713e-09)
PearsonRResult(statistic=0.5206319440555102, pvalue=1.6918488181729874e-15)

<ipython-input-22-5743b0af86b7>:1: DeprecationWarning: Please import `pearsonr` from the `scipy.stats` namespace; the `scipy.stats.stats` namespace is deprecated and will be removed in SciPy 2.0.0.
  from scipy.stats.stats import pearsonr

In [23]:
df_score_exp_0.corr(method='kendall')

,ann_model_0,geval_score_exp_0,prom_score_exp_0,FinGrAct_score_exp_0,geval_score_exp_with_lnk_0,prom_score_exp_with_lnk_0,FinGrAct_score_exp_with_lnk_0
ann_model_0,1.000000,0.117143,0.294259,0.409310,0.207631,0.341175,0.419406
geval_score_exp_0,0.117143,1.000000,0.034645,0.053649,0.549499,-0.044210,0.026214
prom_score_exp_0,0.294259,0.034645,1.000000,0.362451,0.166921,0.466903,0.298780
FinGrAct_score_exp_0,0.409310,0.053649,0.362451,1.000000,0.209752,0.338351,0.683987
geval_score_exp_with_lnk_0,0.207631,0.549499,0.166921,0.209752,1.000000,0.163332,0.225675
prom_score_exp_with_lnk_0,0.341175,-0.044210,0.466903,0.338351,0.163332,1.000000,0.280280
FinGrAct_score_exp_with_lnk_0,0.419406,0.026214,0.298780,0.683987,0.225675,0.280280,1.000000

In [27]:
import scipy.stats as stats

print(kendalltau(df_score_exp_0.ann_model_0.to_list(), df_score_exp_0.geval_score_exp_0.to_list()))
print(kendalltau(df_score_exp_0.ann_model_0.to_list(), df_score_exp_0.prom_score_exp_0.to_list()))
print(kendalltau(df_score_exp_0.ann_model_0.to_list(), df_score_exp_0.FinGrAct_score_exp_0.to_list()))
print(kendalltau(df_score_exp_0.ann_model_0.to_list(), df_score_exp_0.geval_score_exp_with_lnk_0.to_list()))
print(kendalltau(df_score_exp_0.ann_model_0.to_list(), df_score_exp_0.prom_score_exp_with_lnk_0.to_list()))
print(kendalltau(df_score_exp_0.ann_model_0.to_list(), df_score_exp_0.FinGrAct_score_exp_with_lnk_0.to_list()))

SignificanceResult(statistic=0.11714341426026277, pvalue=0.054402942267919197)
SignificanceResult(statistic=0.29425912566162854, pvalue=6.752791574284527e-07)
SignificanceResult(statistic=0.4093097384861609, pvalue=1.8035416601159152e-11)
SignificanceResult(statistic=0.20763139045169063, pvalue=0.0005007607032330583)
SignificanceResult(statistic=0.34117544318405024, pvalue=1.195140346606354e-08)
SignificanceResult(statistic=0.4194055951594053, pvalue=3.0316368501965358e-12)

# for explanations of mistral

In [ ]:
df_score_exp_1 = pd.DataFrame(columns=['ann_model_1', 'geval_score_exp_1', 'prom_score_exp_1', 'FinGrAct_score_exp_1'])
df_score_exp_1['ann_model_1'] = ann_model_1
df_score_exp_1['geval_score_exp_1'] = geval_score_exp_1
df_score_exp_1['prom_score_exp_1'] = prom_score_exp_1
df_score_exp_1['FinGrAct_score_exp_1'] = FinGrAct_score_exp_1
df_score_exp_1['geval_score_exp_with_lnk_1'] = geval_score_exp_with_lnk_1
df_score_exp_1['prom_score_exp_with_lnk_1'] = prom_score_exp_with_lnk_1
df_score_exp_1['FinGrAct_score_exp_with_lnk_1'] = FinGrAct_score_exp_with_lnk_1
df_score_exp_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 7 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ann_model_1                     203 non-null    int64
 1   geval_score_exp_1               203 non-null    int64
 2   prom_score_exp_1                203 non-null    int64
 3   fine_sure_score_exp_1           203 non-null    int64
 4   geval_score_exp_with_lnk_1      203 non-null    int64
 5   prom_score_exp_with_lnk_1       203 non-null    int64
 6   fine_sure_score_exp_with_lnk_1  203 non-null    int64
dtypes: int64(7)
memory usage: 11.2 KB

In [ ]:
df_score_exp_1.corr()

,ann_model_1,geval_score_exp_1,prom_score_exp_1,fine_sure_score_exp_1,geval_score_exp_with_lnk_1,prom_score_exp_with_lnk_1,fine_sure_score_exp_with_lnk_1
ann_model_1,1.000000,0.086104,-0.027575,0.316078,-0.266110,0.221076,0.119979
geval_score_exp_1,0.086104,1.000000,0.069146,0.099850,0.317134,0.113618,0.063203
prom_score_exp_1,-0.027575,0.069146,1.000000,0.106951,-0.000017,0.089149,0.051459
fine_sure_score_exp_1,0.316078,0.099850,0.106951,1.000000,-0.503562,0.197285,0.260961
geval_score_exp_with_lnk_1,-0.266110,0.317134,-0.000017,-0.503562,1.000000,-0.017194,0.074436
prom_score_exp_with_lnk_1,0.221076,0.113618,0.089149,0.197285,-0.017194,1.000000,0.087786
fine_sure_score_exp_with_lnk_1,0.119979,0.063203,0.051459,0.260961,0.074436,0.087786,1.000000

In [ ]:
df_score_exp_1.corr(method='kendall')

,ann_model_1,geval_score_exp_1,prom_score_exp_1,fine_sure_score_exp_1
ann_model_1,1.000000,0.123968,-0.035774,0.205079
geval_score_exp_1,0.123968,1.000000,0.061695,0.123460
prom_score_exp_1,-0.035774,0.061695,1.000000,0.133749
fine_sure_score_exp_1,0.205079,0.123460,0.133749,1.000000

# for explanations of llama

In [ ]:
df_score_exp_2 = pd.DataFrame(columns=['ann_model_2', 'geval_score_exp_2', 'prom_score_exp_2', 'FinGrAct_score_exp_2'])
df_score_exp_2['ann_model_2'] = ann_model_2
df_score_exp_2['geval_score_exp_2'] = geval_score_exp_2
df_score_exp_2['prom_score_exp_2'] = prom_score_exp_2
df_score_exp_2['FinGrAct_score_exp_2'] = FinGrAct_score_exp_2
#df_score_exp_2['geval_score_exp_with_lnk_2'] = geval_score_exp_with_lnk_2
#df_score_exp_2['prom_score_exp_with_lnk_2'] = prom_score_exp_with_lnk_2
#df_score_exp_2['FinGrAct_score_exp_with_lnk_2'] = FinGrAct_score_exp_with_lnk_2
df_score_exp_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ann_model_2            203 non-null    int64
 1   geval_score_exp_2      203 non-null    int64
 2   prom_score_exp_2       203 non-null    int64
 3   fine_sure_score_exp_2  203 non-null    int64
dtypes: int64(4)
memory usage: 6.5 KB

In [ ]:
df_score_exp_2.corr()

,ann_model_2,geval_score_exp_2,prom_score_exp_2,fine_sure_score_exp_2
ann_model_2,1.000000,0.037904,0.199575,0.428191
geval_score_exp_2,0.037904,1.000000,0.009881,-0.023160
prom_score_exp_2,0.199575,0.009881,1.000000,0.054746
fine_sure_score_exp_2,0.428191,-0.023160,0.054746,1.000000

In [ ]:
df_score_exp_2.corr(method='kendall')

,ann_model_2,geval_score_exp_2,prom_score_exp_2,fine_sure_score_exp_2
ann_model_2,1.000000,0.096968,0.177433,0.356235
geval_score_exp_2,0.096968,1.000000,0.017075,-0.094368
prom_score_exp_2,0.177433,0.017075,1.000000,0.057711
fine_sure_score_exp_2,0.356235,-0.094368,0.057711,1.000000

# for explanations of gpt-4

In [ ]:
df_score_exp_3 = pd.DataFrame(columns=['ann_model_3', 'geval_score_exp_3', 'prom_score_exp_3', 'FinGrAct_score_exp_3'])
df_score_exp_3['ann_model_3'] = ann_model_3
df_score_exp_3['geval_score_exp_3'] = geval_score_exp_3
df_score_exp_3['prom_score_exp_3'] = prom_score_exp_3
df_score_exp_3['FinGrAct_score_exp_3'] = FinGrAct_score_exp_3
#df_score_exp_3['geval_score_exp_with_lnk_3'] = geval_score_exp_with_lnk_3
#df_score_exp_3['prom_score_exp_with_lnk_3'] = prom_score_exp_with_lnk_3
#df_score_exp_3['FinGrAct_score_exp_with_lnk_3'] = FinGrAct_score_exp_with_lnk_3
df_score_exp_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ann_model_3            203 non-null    int64
 1   geval_score_exp_3      203 non-null    int64
 2   prom_score_exp_3       203 non-null    int64
 3   fine_sure_score_exp_3  203 non-null    int64
dtypes: int64(4)
memory usage: 6.5 KB

In [ ]:
df_score_exp_3.corr()

,ann_model_3,geval_score_exp_3,prom_score_exp_3,fine_sure_score_exp_3
ann_model_3,1.000000,0.041947,0.158372,0.437284
geval_score_exp_3,0.041947,1.000000,0.053087,0.049725
prom_score_exp_3,0.158372,0.053087,1.000000,0.170470
fine_sure_score_exp_3,0.437284,0.049725,0.170470,1.000000

In [ ]:
df_score_exp_3.corr(method='kendall')

,ann_model_3,geval_score_exp_3,prom_score_exp_3,fine_sure_score_exp_3
ann_model_3,1.000000,0.064389,0.119081,0.311563
geval_score_exp_3,0.064389,1.000000,0.037057,0.102601
prom_score_exp_3,0.119081,0.037057,1.000000,0.187894
fine_sure_score_exp_3,0.311563,0.102601,0.187894,1.000000