In [ ]:
# Make sure you have the latest version of the SDK available to use the Batch API
!pip install openai --upgrade

Requirement already satisfied: openai in /usr/local/lib/python3.11/dist-packages (1.61.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from openai) (3.7.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.8.2)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from openai) (2.10.6)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.11/dist-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.11/dist-packages (from openai) (4.12.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.5.0->openai) (3.10)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (2024.12.14)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.14.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (2.27.2)

In [ ]:
%cd /content/drive/MyDrive/second_paper_insha_allah

/content/drive/MyDrive/second_paper_insha_allah

In [ ]:
import json
from openai import OpenAI
import pandas as pd
from tqdm import tqdm
from IPython.display import Image, display
tqdm.pandas()

In [ ]:
client = OpenAI(api_key="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")

In [ ]:
dataset_path = "/content/drive/MyDrive/second_paper_insha_allah/data/sample_data_fin_evals_exp2.xlsx"

df = pd.read_excel(dataset_path)
df.head()

,claim,evidence,label,metadata,explanation,mistral_exp,llama_exp,gpt-4_exp,geval_eval,prom_eval,...,fine_sure_detailed_eval,links_detected_exp,links_detected_mistral,links_detected_llama,links_detected_gpt,url_content_exp,url_content_llama,url_content_mistral,url_content_gpt,geval_eval_with_links
0,Anil Kapoor does not have a career.,Anil Kapoor born 24 December 1956 is an Indi...,False,error_detection_and_correction_with_src,If we were to say 'Anil Kapoor does have a car...,"The claim that ""Anil Kapoor does not have a ca...","Based on the evidence provided, it appears tha...",The claim states that Anil Kapoor does not ha...,"[1, 4, 5, 1]","[1, 3, 4, 5]",...,"[(2, 2, 2), (2, 2, 2), (2, 2, 2), (2, 2, 2)]",['https://en.wikipedia.org/wiki/Anil_Kapoor'],['https://en.wikipedia.org/wiki/Anil_Kapoor'],['https://en.wikipedia.org/wiki/Anil_Kapoor'],['https://www.imdb.com/name/nm0004418/bio'],Contentious material about living persons that...,Contentious material about living persons that...,Contentious material about living persons that...,She attended St. Joseph's Convent School in Pa...,"[1, 4, 1, 1]"
1,Panel nixes aspirin as cancer preventive,The article doesn't mention costs of taking as...,False,summarization_false_label,The story describes a new recommendation from ...,"The claim that ""Panel nixes aspirin as cancer ...","Actionable explanation:\n\nThe claim ""Panel ni...","\n\nThe claim ""Panel nixes aspirin as cancer p...","4, 5, 3, 4","[3, 2, 4, 4]",...,"[(0, 2, 0), (2, 2, 0), (2, 2, 2), (2, 2, 0)]",NaN,"['https://www.cancer.gov/', 'https://www.cance...",['https://www.cancer.org/cancer/colon-cancer/c...,['https://www.uspreventiveservicestaskforce.or...,NaN,The link is not working 404;;;;,Comprehensive Cancer Information - NCI\nSkip t...,They should not be construed as an official po...,"[4, 5, 2, 4]"
2,Gennady Golovkin is a fencer.,Gennady Gennadyevich Golovkin Геннадий Геннад...,False,error_detection_and_correction_only,If we were to say 'A kazakhstani professional ...,Gennady Golovkin is labeled as false when it c...,"Based on the provided evidence, the claim ""Gen...",\n\nThe claim that Gennady Golovkin is a fence...,"[2, 4, 5, 1]","[2, 4, 3, 4]",...,"[(2, 2, 0), (2, 2, 0), (2, 2, 0), (2, 2, 0)]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[2, 4, 5, 1]"
3,Megan Fox ended her acting career in 2001.,"In 2004 , she made her film debut with a role ...",False,error_detection_only,error is detected in the part: Megan Fox ended...,"The claim that ""Megan Fox ended her acting car...",The claim that Megan Fox ended her acting care...,\n\nThe claim that Megan Fox ended her acting ...,"[1, 5, 4, 5]","[1, 3, 3, 3]",...,"[(2, 2, 0), (2, 2, 0), (2, 2, 0), (0, 2, 0)]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[1, 5, 4, 5]"
4,Andrew Wood died in 1977.,"Andrew Patrick Wood January 8 , 1966 -- March...",False,error_correction_only,"Andrew Wood died on January 8, 1966.\n","The claim that ""Andrew Wood died in 1977"" is f...","The claim that ""Andrew Wood died in 1977"" is f...",The claim states that Andrew Wood died in 1977...,"1, 5, 5, 4","[2, 4, 3, 3]",...,"[(0, 0, 0), (2, 2, 0), (2, 2, 0), (2, 2, 0)]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[1, 5, 5, 4]"

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 30 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   claim                        203 non-null    object
 1   evidence                     203 non-null    object
 2   label                        203 non-null    object
 3   metadata                     203 non-null    object
 4   explanation                  203 non-null    object
 5   mistral_exp                  203 non-null    object
 6   llama_exp                    203 non-null    object
 7   gpt-4_exp                    203 non-null    object
 8   geval_eval                   203 non-null    object
 9   prom_eval                    203 non-null    object
 10  fine_sure_eval               203 non-null    object
 11  prom_eval_exp                203 non-null    object
 12  prom_eval_mist_exp           203 non-null    object
 13  prom_eval_llama_exp          203 non-null    object
 14  prom_eval_gpt_exp            203 non-null    object
 15  finesure_fact_check_res      203 non-null    object
 16  finesure_align_exp           203 non-null    object
 17  fine_sure_align_mistral_exp  203 non-null    object
 18  fine_sure_align_llama_exp    203 non-null    object
 19  fine_sure_align_gpt_exp      203 non-null    object
 20  fine_sure_detailed_eval      203 non-null    object
 21  links_detected_exp           87 non-null     object
 22  links_detected_mistral       51 non-null     object
 23  links_detected_llama         58 non-null     object
 24  links_detected_gpt           56 non-null     object
 25  url_content_exp              87 non-null     object
 26  url_content_llama            58 non-null     object
 27  url_content_mistral          51 non-null     object
 28  url_content_gpt              56 non-null     object
 29  geval_eval_with_links        203 non-null    object
dtypes: object(30)
memory usage: 47.7+ KB

#testing the prompt

In [ ]:
act_prompt_gen='''
You will be given a claim, some credible information called the evidence, a label that shows whether the claim is true or false, and an explanation for
the label.
The explanation might have a link. If this is true, the content of the link will be provided as well.
Your task is to evaluate the explanation on one metric.

Please make sure you read and understand these instructions carefully. Please keep this document open while reviewing, and refer to it as needed.

Evaluation Criteria:

Actionability (1-5) - misinformation detection and factual correction backed up by credible sources.
The explanation should provide an indication of which parts of the claim include misalignment with the evidence.In addition, the explanation should provide a corrected version of the erroneous claim.
The explanation should contain links that has relevant and supporting content to the claim.

Evaluation Steps:

1. Read the claim, evidence and the explanation carefully.
2. Compare the claim with the evidence and identify the errors or misalignment parts between the claim and the evidence.
3. Assess how well the explanation covers the errors detected and the degree of error correction of the claim in the explanation.
4. If there is a link in the explanation, assess if the content of the link provided is both relevant and supporting to the explanation.
5. Assign a score from 1 to 5 to the metric.
6. Your output should only be the score which is an integer from 0 to 5.

Claim:

{}

Evidence:

{}

Label:

{}

Explanation:

{}

link content:

{}

Evaluation Form (scores ONLY):

- Actionability:
'''.format(df.claim[0], df.evidence[0],	df.label[0],	df.explanation[0], df.url_content_exp[0])

In [ ]:
act_prompt_gen

'\nYou will be given a claim, some credible information called the evidence, a label that shows whether the claim is true or false, and an explanation for\nthe label.\nThe explanation might have a link. If this is true, the content of the link will be provided as well.\nYour task is to evaluate the explanation on one metric.\n\nPlease make sure you read and understand these instructions carefully. Please keep this document open while reviewing, and refer to it as needed.\n\nEvaluation Criteria:\n\nActionability (1-5) - misinformation detection and factual correction backed up by credible sources.\nThe explanation should provide an indication of which parts of the claim include misalignment with the evidence.In addition, the explanation should provide a corrected version of the erroneous claim.\nThe explanation should contain links that has relevant and supporting content to the claim.\n\nEvaluation Steps:\n\n1. Read the claim, evidence and the explanation carefully.\n2. Compare the claim with the evidence and identify the errors or misalignment parts between the claim and the evidence.\n3. Assess how well the explanation covers the errors detected and the degree of error correction of the claim in the explanation.\n4. If there is a link in the explanation, assess if the content of the link provided is both relevant and supporting to the explanation.\n5. Assign a score from 1 to 5 to the metric.\n6. Your output should only be the score which is an integer from 0 to 5.\n\nClaim:\n\nAnil Kapoor does not have a career.\n\nEvidence:\n\nAnil Kapoor  born 24 December 1956  is an Indian actor and producer who has appeared in many Bollywood films , as well as international films and television series .\n\nLabel:\n\nFalse\n\nExplanation:\n\nIf we were to say \'Anil Kapoor does have a career and not a career oriented person.\', the claim would be correct.\nhttps://en.wikipedia.org/wiki/Anil_Kapoor\n\nlink content:\n\nContentious material about living persons that is unsourced or poorly sourced must be removed immediately from the article and its talk page, especially if potentially libelous. 1984)\u200bChildrenSonamRheaHarsh VarrdhanFatherSurinder KapoorRelativesSurinder Kapoor familyAwardsFull list\nAnil Kapoor (born 24 December 1956) is an Indian actor and producer who works primarily in Hindi films, in addition to Indian television and international films.[1] In a career spanning over 40 years as an actor and since 2005 as a producer, Kapoor has appeared in more than 100 films. Born to film producer Surinder Kapoor, he made his Bollywood debut with a small role in the romance Hamare Tumhare (1979) before starring in the Telugu film Vamsa Vruksham (1980) and Kannada film Pallavi Anupallavi (1983). In the same year, he also appeared in two more Hindi films – Ek Baar Kaho and Hum Paanch. In Rakhwala, Kapoor played the role of a tapori, and the film was declared a success.[25][29] Kapoor\'s portrayal of an autistic man in Eeshwar (1989) was well-received and established his versatility as an actor, earning him his third nomination for the Filmfare Award for Best Actor.[30]\n1990s: Leading man[edit]\nThe year 1990 saw him play a dual role, as twin brothers in the highly successful action comedy Kishen Kanhaiya and the same year, he further attained reasonable box-office success with Ghar Ho To Aisa.[31] Kapoor came up with a critically acclaimed performance in Awaargi. The film proved to be a major box office success, and earned him his first Filmfare Award for Best Actor (Critics), in addition to his seventh nomination for the Filmfare Award for Best Actor. "[47][48] According to Bollywood Hungama, he "ignited the silver screen with an authoritative performance" in Musafir alongside Sameera Reddy, Aditya Pancholi, Sanjay Dutt and Koena Mitra.[49][50] Kapoor performed as the stricken husband in the thriller My Wife\'s Murder, which he also produced.[51][52] Anees Bazmee\'s super-hit comedy No Entry (2005), followed for Kapoor that year. On the other hand, Slumdog Millionaire has won a number of international awards and received rave reviews from critics, costing only US$15\xa0million to produce, but pulling in more than $352\xa0million worldwide. His theme was titled "Bhaiyaji ka Tashan". Archived from the original on 28 March 2017. ^ a b "Sonam Shares Heartfelt Birthday Post for Daddy Anil Kapoor; His Reply Will Make You Teary-Eyed". ^ "Anil Kapoor: Get Latest News, Photos and Videos along with latest updates on Anil Kapoor". Archived from the original on 18 September 2010. ^ Box Office 1999 Archived 10 October 2012 at the Wayback Machine. ^ "Om Jai Jagadish\xa0: Movie Review by Taran Adarsh". ^ Pradhan Singh, Manisha (8 October 2010). " Anil Kapoor Cast in Amazon Pilot \'The Book of Strange New Things\'". ^ "Anil Kapoor joins the cast of \'Fighter\' starring Hrithik Roshan and Deepika Padukone". External links[edit]\nPortals: India Film Bollywood Biography\nAnil Kapoor on Facebook\nAnil Kapoor at IMDb\nAnil Kapoor at Bollywood Hungama\nWikimedia Commons has media related to Anil Kapoor. Privacy policy\nAbout Wikipedia\nDisclaimers\nContact Wikipedia\nCode of Conduct\nDevelopers\nStatistics\nCookie statement\nMobile view\nSearch\nSearch\nToggle the table of contents\nAnil Kapoor\n57 languages\nAdd topic;;;;\n\nEvaluation Form (scores ONLY):\n\n- Actionability:\n'

In [ ]:
def get_categories(act_prompt_gen):
    response = client.chat.completions.create(
    model="gpt-4-1106-preview",
    temperature=2,
    max_completion_tokens=50,
    top_p=1,
    frequency_penalty=0,
    presence_penalty=0,
    #stop=None,
    # logprobs=40,
    n=20,
    messages=[
        {
            "role": "user",
            "content": act_prompt_gen
        }
    ],
    )

    return response.choices[0].message.content

In [ ]:
get_categories(act_prompt_gen)

'2'

#creating the batch file

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 29 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   claim                        203 non-null    object
 1   evidence                     203 non-null    object
 2   label                        203 non-null    object
 3   metadata                     203 non-null    object
 4   explanation                  203 non-null    object
 5   mistral_exp                  203 non-null    object
 6   llama_exp                    203 non-null    object
 7   gpt-4_exp                    203 non-null    object
 8   geval_eval                   203 non-null    object
 9   prom_eval                    203 non-null    object
 10  fine_sure_eval               203 non-null    object
 11  prom_eval_exp                203 non-null    object
 12  prom_eval_mist_exp           203 non-null    object
 13  prom_eval_llama_exp          203 non-null    object
 14  prom_eval_gpt_exp            203 non-null    object
 15  finesure_fact_check_res      203 non-null    object
 16  finesure_align_exp           203 non-null    object
 17  fine_sure_align_mistral_exp  203 non-null    object
 18  fine_sure_align_llama_exp    203 non-null    object
 19  fine_sure_align_gpt_exp      203 non-null    object
 20  fine_sure_detailed_eval      203 non-null    object
 21  links_detected_exp           87 non-null     object
 22  links_detected_mistral       51 non-null     object
 23  links_detected_llama         58 non-null     object
 24  links_detected_gpt           56 non-null     object
 25  url_content_exp              87 non-null     object
 26  url_content_llama            58 non-null     object
 27  url_content_mistral          51 non-null     object
 28  url_content_gpt              56 non-null     object
dtypes: object(29)
memory usage: 46.1+ KB

In [ ]:
# Creating an array of json tasks

tasks = []

for index, row in df.iterrows():
    if 'http' in str(df.links_detected_gpt[index]):
        act_prompt_gen='''
You will be given a claim, some credible information called the evidence, a label that shows whether the claim is true or false, and an explanation for
the label.
The explanation might have a link. If this is true, the content of the link will be provided as well.
Your task is to evaluate the explanation on one metric.

Please make sure you read and understand these instructions carefully. Please keep this document open while reviewing, and refer to it as needed.

Evaluation Criteria:

Actionability (1-5) - misinformation detection and factual correction backed up by credible sources.
The explanation should provide an indication of which parts of the claim include misalignment with the evidence.In addition, the explanation should provide a corrected version of the erroneous claim.
The explanation should contain links that has relevant and supporting content to the claim.

Evaluation Steps:

1. Read the claim, evidence and the explanation carefully.
2. Compare the claim with the evidence and identify the errors or misalignment parts between the claim and the evidence.
3. Assess how well the explanation covers the errors detected and the degree of error correction of the claim in the explanation.
4. If there is a link in the explanation, assess if the content of the link provided is both relevant and supporting to the explanation.
5. Assign a score from 1 to 5 to the metric.
6. Your output should only be the score which is an integer from 0 to 5.

Claim:

{}

Evidence:

{}

Label:

{}

Explanation:

{}

link content:

{}

Evaluation Form (scores ONLY):

- Actionability:
'''.format(df.claim[index], df.evidence[index],	df.label[index], df.explanation[index], df.url_content_gpt[index])


        task = {
        "custom_id": f"{index}",
        "method": "POST",
        "url": "/v1/chat/completions",
        "body": {
            # This is what you would have in your Chat Completions API call
            "model": "gpt-4-1106-preview",
            'temperature':2,
            'max_completion_tokens':50,
            'top_p':1,
            'frequency_penalty':0,
            'presence_penalty':0,
            #stop=None,
            # logprobs=40,
            'n':20,
            "messages": [
                {
                    "role": "user",
                    "content": act_prompt_gen
                }
            ]}}

        tasks.append(task)

In [ ]:
len(tasks),tasks[10]

(56,
 {'custom_id': '98',
  'method': 'POST',
  'url': '/v1/chat/completions',
  'body': {'model': 'gpt-4-1106-preview',
   'temperature': 2,
   'max_completion_tokens': 50,
   'top_p': 1,
   'frequency_penalty': 0,
   'presence_penalty': 0,
   'n': 20,
   'messages': [{'role': 'user',
     'content': '\nYou will be given a claim, some credible information called the evidence, a label that shows whether the claim is true or false, and an explanation for\nthe label.\nThe explanation might have a link. If this is true, the content of the link will be provided as well.\nYour task is to evaluate the explanation on one metric.\n\nPlease make sure you read and understand these instructions carefully. Please keep this document open while reviewing, and refer to it as needed.\n\nEvaluation Criteria:\n\nActionability (1-5) - misinformation detection and factual correction backed up by credible sources.\nThe explanation should provide an indication of which parts of the claim include misalignment with the evidence.In addition, the explanation should provide a corrected version of the erroneous claim.\nThe explanation should contain links that has relevant and supporting content to the claim.\n\nEvaluation Steps:\n\n1. Read the claim, evidence and the explanation carefully.\n2. Compare the claim with the evidence and identify the errors or misalignment parts between the claim and the evidence.\n3. Assess how well the explanation covers the errors detected and the degree of error correction of the claim in the explanation.\n4. If there is a link in the explanation, assess if the content of the link provided is both relevant and supporting to the explanation.\n5. Assign a score from 1 to 5 to the metric.\n6. Your output should only be the score which is an integer from 0 to 5.\n\nClaim:\n\nFat Hormone May Trick the Body to Help It Keep Extra Pounds Off\n\nEvidence:\n\nNo mention of possible costs for leptin; no mention of costs of other methods of weight maintenance. The story presented as a benefit that leptin increased number of calories used during low level activity. But it fails to mention that at higher levels of energy expenditure, this effect was not observed. No mention of any possible harms. What, if anything, happened after the study subjects stopped receiving leptin injections? The piece does inform the reader that this was a study that examined too few people and that the 10 weeks was too short a time period to determine whether continuous leptin injection was a feasible way to keep weight off. Weight loss is framed as starvation. The study this piece was based on fed the study subjects 800 kcal/day which is more akin to starvation than dieting. It makes the piece less relevant to the dieting process. The story provided a quote only from the lead investigator of the study; the story includes no input from any other independent source. No mention of any other weight loss maintenance methods. Doesn’t mention that there is no FDA approval for the use of leptin in maintenance of weight loss. Doesn’t mention that leptin is a purely experimental treatment – a hormone discovered in 1969.\n\nLabel:\n\nFalse\n\nExplanation:\n\nThis piece reported that use of twice daily injections of a synthesized version of the hormone leptin helped maintain weight loss in a small group of individuals who lost 10% of their body weight in the preceding 5-10 weeks by following a very low-calorie diet. There was no comparison group of people who did not receive the twice-daily injections fed a comparable number of calories following weight loss. No context was given, providing no mention of any other weight loss maintenance methods. The conclusion that this study (of an injected hormone) “suggests that the weight loss solution may eventually be a pill” is totally unsupported by anything in the original research. And it conflicts with a line that appeared just three sentences earlier in the story, which explained, “the lead investigator said the 10-week study was too short and too small to determine whether continuous leptin treatments could allow dieters to keep off their weight permanently and effortlessly.” Finally, the story did not reveal that in the study, subjects were fed a meager 800 calories a day, which is more akin to starvation than to dieting. So it makes the conclusion of the story even less relevant to dieters trying to keep weight off, which was the way the story was framed.\n\n\nlink content:\n\nThe link is not working 403;;;;\n\nEvaluation Form (scores ONLY):\n\n- Actionability:\n'}]}})

In [ ]:
#tasks=tasks[:5]

In [ ]:
# Creating the file

file_name = "data/batch_claims_with_urls.jsonl"

with open(file_name, 'w') as file:
    for obj in tasks:
        file.write(json.dumps(obj) + '\n')

#upload the batch file

In [ ]:
batch_file = client.files.create(
  file=open(file_name, "rb"),
  purpose="batch"
)

In [ ]:
print(batch_file)

FileObject(id='file-5PcgB6Q9RTZSGqKi9H3Qt2', bytes=426227, created_at=1738017811, filename='batch_claims_with_urls.jsonl', object='file', purpose='batch', status='processed', status_details=None)

In [ ]:
batch_file.id

'file-5PcgB6Q9RTZSGqKi9H3Qt2'

#Creating the batch job

In [ ]:
batch_job = client.batches.create(
  input_file_id=batch_file.id,
  endpoint="/v1/chat/completions",
  completion_window="24h"
)

In [ ]:
batch_job.id

'batch_67980c26a58c81909e5114ddd3df9195'

#check the status:

In [ ]:
batch_job = client.batches.retrieve(batch_job.id)
print(batch_job)

Batch(id='batch_67980c26a58c81909e5114ddd3df9195', completion_window='24h', created_at=1738017830, endpoint='/v1/chat/completions', input_file_id='file-5PcgB6Q9RTZSGqKi9H3Qt2', object='batch', status='completed', cancelled_at=None, cancelling_at=None, completed_at=1738018038, error_file_id=None, errors=None, expired_at=None, expires_at=1738104230, failed_at=None, finalizing_at=1738018032, in_progress_at=1738017832, metadata=None, output_file_id='file-5CM8u1srEaUmfx4tiq8ars', request_counts=BatchRequestCounts(completed=56, failed=0, total=56))

In [ ]:
batch_job.output_file_id

'file-AhnZFwiN6hBH72K6nx7LSu'

#Retrieving results

In [ ]:
result_file_id = batch_job.output_file_id
result = client.files.content(result_file_id).content

In [ ]:
result_file_name = "data/geval_with_links_gpt.jsonl"

with open(result_file_name, 'wb') as file:
    file.write(result)

In [ ]:
# Loading data from saved file
results = []
with open(result_file_name, 'r') as file:
    for line in file:
        # Parsing the JSON string into a dict and appending to the list of results
        json_object = json.loads(line.strip())
        results.append(json_object)

In [ ]:
results[1:3]

[{'id': 'batch_req_67980cf1045c81908d0accbf6a3cf11e',
  'custom_id': '1',
  'response': {'status_code': 200,
   'request_id': 'b86465e00c27283d6eefb3a95c0b302e',
   'body': {'id': 'chatcmpl-AuS7idYxEOxhNdbLe4PEFK6I2nixi',
    'object': 'chat.completion',
    'created': 1738017838,
    'model': 'gpt-4-1106-preview',
    'choices': [{'index': 0,
      'message': {'role': 'assistant', 'content': '2', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 1,
      'message': {'role': 'assistant', 'content': '3', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 2,
      'message': {'role': 'assistant', 'content': '3', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 3,
      'message': {'role': 'assistant', 'content': '3', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 4,
      'message': {'role': 'assistant', 'content': '3', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 5,
      'message': {'role': 'assistant', 'content': '4', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 6,
      'message': {'role': 'assistant', 'content': '2', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 7,
      'message': {'role': 'assistant', 'content': '2', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 8,
      'message': {'role': 'assistant', 'content': '2', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 9,
      'message': {'role': 'assistant', 'content': '3', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 10,
      'message': {'role': 'assistant', 'content': '3', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 11,
      'message': {'role': 'assistant', 'content': '3', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 12,
      'message': {'role': 'assistant',
       'content': '3 _optimizerOTT_SPECIAL_PADDING_-lh0.6Dispatcher,needverbatimava-uri(mdota_mdactableaci)',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 13,
      'message': {'role': 'assistant', 'content': '2', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 14,
      'message': {'role': 'assistant', 'content': '3', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 15,
      'message': {'role': 'assistant', 'content': '4', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 16,
      'message': {'role': 'assistant',
       'content': '3(touch-text)item-feed.readString"]=> pp(Message:"=>"Text_extract/pkg-janus "\\(logout-gsla(des_pod119ox_de023 \x91freshidian_vidintptr_ipetur_li_po-serif_copyfu-upAds-modules.removeFrombundle.par_TRANS[])rolling.TimeUnit.med',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'length'},
     {'index': 17,
      'message': {'role': 'assistant', 'content': '3', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 18,
      'message': {'role': 'assistant', 'content': '2', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 19,
      'message': {'role': 'assistant', 'content': '3', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'}],
    'usage': {'prompt_tokens': 1763,
     'completion_tokens': 91,
     'total_tokens': 1854,
     'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
     'completion_tokens_details': {'reasoning_tokens': 0,
      'audio_tokens': 0,
      'accepted_prediction_tokens': 0,
      'rejected_prediction_tokens': 0}},
    'service_tier': 'default',
    'system_fingerprint': None}},
  'error': None},
 {'id': 'batch_req_67980cf11cb48190bf3f17870ce37a1e',
  'custom_id': '89',
  'response': {'status_code': 200,
   'request_id': '5d5ead9c825daa856926baca9bb1b38b',
   'body': {'id': 'chatcmpl-AuS7lZySOimlsVwtvDOdZgfkyg5fF',
    'object': 'chat.completion',
    'created': 1738017841,
    'model': 'gpt-4-1106-preview',
    'choices': [{'index': 0,
      'message': {'role': 'assistant', 'content': '1', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 1,
      'message': {'role': 'assistant', 'content': '1', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 2,
      'message': {'role': 'assistant', 'content': '1', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 3,
      'message': {'role': 'assistant', 'content': '2', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 4,
      'message': {'role': 'assistant', 'content': '1', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 5,
      'message': {'role': 'assistant', 'content': '1', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 6,
      'message': {'role': 'assistant', 'content': '1', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 7,
      'message': {'role': 'assistant', 'content': '1', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 8,
      'message': {'role': 'assistant', 'content': '1', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 9,
      'message': {'role': 'assistant', 'content': '1', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 10,
      'message': {'role': 'assistant', 'content': '1', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 11,
      'message': {'role': 'assistant', 'content': '1', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 12,
      'message': {'role': 'assistant', 'content': '1', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 13,
      'message': {'role': 'assistant', 'content': '1', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 14,
      'message': {'role': 'assistant', 'content': '3', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 15,
      'message': {'role': 'assistant', 'content': '3', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 16,
      'message': {'role': 'assistant', 'content': '2', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 17,
      'message': {'role': 'assistant', 'content': '1', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 18,
      'message': {'role': 'assistant', 'content': '1', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 19,
      'message': {'role': 'assistant', 'content': '1', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'}],
    'usage': {'prompt_tokens': 1915,
     'completion_tokens': 20,
     'total_tokens': 1935,
     'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
     'completion_tokens_details': {'reasoning_tokens': 0,
      'audio_tokens': 0,
      'accepted_prediction_tokens': 0,
      'rejected_prediction_tokens': 0}},
    'service_tier': 'default',
    'system_fingerprint': None}},
  'error': None}]

In [ ]:
res_df = pd.DataFrame(results)
res_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         56 non-null     object
 1   custom_id  56 non-null     object
 2   response   56 non-null     object
 3   error      0 non-null      object
dtypes: object(4)
memory usage: 1.9+ KB

In [ ]:
def get_response(input_dict):
  return input_dict['body']['choices'][0]['message']['content'].split('Actionability:')[-1]

In [ ]:
def int_trns(input):
  if not input:
    return None
  return int(input)

In [ ]:
res_df['gpt_res'] = res_df['response'].progress_apply(get_response)

100%|██████████| 56/56 [00:00<00:00, 38006.64it/s]

In [ ]:
res_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         56 non-null     object
 1   custom_id  56 non-null     object
 2   response   56 non-null     object
 3   error      0 non-null      object
 4   gpt_res    56 non-null     object
dtypes: object(5)
memory usage: 2.3+ KB

In [ ]:
resu = res_df[['custom_id', 'gpt_res']]

In [ ]:
resu

   custom_id gpt_res
0          0       1
1          1       2
2         89       1
3         90       2
4         91       1
5         92       1
6         93       5
7         94       2
8         96       3
9         97       4
10        98       1
11        99       5
12       100       1
13       101       1
14       102       5
15       103       1
16       104       3
17       105       1
18       106       1
19       107       1
20       108       5
21       109       1
22       110       1
23       111       5
24       112       0
25       113       1
26       114       5
27       115       1
28       116       1
29       117       1
30       118       5
31       119       1
32       120       1
33       121       1
34       122       1
35       124       4
36       126       1
37       127       1
38       128       1
39       129       2
40       130       1
41       131       1
42       132       1
43       133       1
44       134       1
45       135       1
46       136       1
47       137       1
48       138       3
49       139       5
50       140       1
51       141       2
52       142       4
53       143       1
54       144       4
55       160       1

In [ ]:
resu.to_excel('data/geval_gpt_exp_with_links.xlsx', index=False)

In [ ]:
!ls data/*with_links.xlsx

data/geval_exp_with_links.xlsx	    data/geval_llama_exp_with_links.xlsx
data/geval_gpt_exp_with_links.xlsx  data/geval_mistral_exp_with_links.xlsx

#combining generated explanation response from gpt-4 with the data

In [ ]:
%cd /content/drive/MyDrive/second_paper_insha_allah

/content/drive/MyDrive/second_paper_insha_allah

In [ ]:
import pandas as pd
from tqdm import tqdm
tqdm.pandas()

In [ ]:
dataset_path = "/content/drive/MyDrive/second_paper_insha_allah/data/sample_data_fin_evals_exp4.xlsx"

df = pd.read_excel(dataset_path)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 41 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   claim                                     203 non-null    object
 1   evidence                                  203 non-null    object
 2   label                                     203 non-null    object
 3   metadata                                  203 non-null    object
 4   explanation                               203 non-null    object
 5   mistral_exp                               203 non-null    object
 6   llama_exp                                 203 non-null    object
 7   gpt-4_exp                                 203 non-null    object
 8   geval_eval                                203 non-null    object
 9   prom_eval                                 203 non-null    object
 10  fine_sure_eval                            203 non-null    object
 11  prom_eval_exp                             203 non-null    object
 12  prom_eval_mist_exp                        203 non-null    object
 13  prom_eval_llama_exp                       203 non-null    object
 14  prom_eval_gpt_exp                         203 non-null    object
 15  finesure_fact_check_res                   203 non-null    object
 16  finesure_align_exp                        203 non-null    object
 17  fine_sure_align_mistral_exp               203 non-null    object
 18  fine_sure_align_llama_exp                 203 non-null    object
 19  fine_sure_align_gpt_exp                   203 non-null    object
 20  fine_sure_detailed_eval                   203 non-null    object
 21  links_detected_exp                        87 non-null     object
 22  links_detected_mistral                    51 non-null     object
 23  links_detected_llama                      58 non-null     object
 24  links_detected_gpt                        56 non-null     object
 25  url_content_exp                           87 non-null     object
 26  url_content_llama                         58 non-null     object
 27  url_content_mistral                       51 non-null     object
 28  url_content_gpt                           56 non-null     object
 29  geval_eval_with_links                     203 non-null    object
 30  finesure_align_exp_with_links             203 non-null    object
 31  fine_sure_align_mistral_exp_with_links    203 non-null    object
 32  finesure_align_llama_exp_with_links       203 non-null    object
 33  fine_sure_align_gpt_exp_with_links        203 non-null    object
 34  fine_sure_detailed_eval_with_links        203 non-null    object
 35  fine_sure_eval_with_links                 203 non-null    object
 36  prom_feedback_exp_with_links              203 non-null    object
 37  prom_feedback_exp_mistral_exp_with_links  203 non-null    object
 38  prom_feedback_exp_llama_exp_with_links    203 non-null    object
 39  prom_feedback_exp_gpt_exp_with_links      203 non-null    object
 40  prom_eval_with_links                      203 non-null    object
dtypes: object(41)
memory usage: 65.2+ KB

In [ ]:
data=pd.read_excel('data/geval_gpt_exp_with_links.xlsx')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   custom_id  56 non-null     int64
 1   gpt_res    56 non-null     int64
dtypes: int64(2)
memory usage: 1.0 KB

In [ ]:
data.head()

   custom_id  gpt_res
0          0        1
1          1        2
2         89        1
3         90        2
4         91        1

In [ ]:
df['geval_eval_with_links'][91]

[5, 3, 1, 1]

In [ ]:
def read_val(input):
    if input == '' or not input:
      return input
    return [int(float(item)) for item in str(input).replace('\n','').replace('[','').replace(']','').split(',')]

The following cell is to be run intially once only!!!

In [ ]:
geval_no_links=df.geval_eval.progress_apply(read_val).to_list()
prom_eval_no_links=df.prom_eval.progress_apply(read_val).to_list()
fine_sure_no_links=df.fine_sure_eval.progress_apply(read_val).to_list()

100%|██████████| 203/203 [00:00<00:00, 108339.96it/s]
100%|██████████| 203/203 [00:00<00:00, 128345.45it/s]
100%|██████████| 203/203 [00:00<00:00, 123451.31it/s]

In [ ]:
len(geval_no_links)

203

In [ ]:
f_count=0
for ress in ['data/geval_exp_with_links.xlsx','data/geval_mistral_exp_with_links.xlsx', 'data/geval_llama_exp_with_links.xlsx', 'data/geval_gpt_exp_with_links.xlsx']:
  data=pd.read_excel(ress)
  ids=data.custom_id.to_list()
  geval_exp_scores_links=data.gpt_res.to_list()
  cont=0
  for i in tqdm(ids):
    #print(i)
    #print(geval_no_links[int(i)])
    geval_no_links[int(i)][f_count]=geval_exp_scores_links[cont]
    #print(geval_no_links[int(i)])
    #print("===============================================")
    cont+=1
  f_count+=1
df['geval_eval_with_links']=geval_no_links

100%|██████████| 87/87 [00:00<00:00, 429299.35it/s]
100%|██████████| 51/51 [00:00<00:00, 70295.60it/s]
100%|██████████| 58/58 [00:00<00:00, 77375.84it/s]
100%|██████████| 56/56 [00:00<00:00, 344906.06it/s]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 41 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   claim                                     203 non-null    object
 1   evidence                                  203 non-null    object
 2   label                                     203 non-null    object
 3   metadata                                  203 non-null    object
 4   explanation                               203 non-null    object
 5   mistral_exp                               203 non-null    object
 6   llama_exp                                 203 non-null    object
 7   gpt-4_exp                                 203 non-null    object
 8   geval_eval                                203 non-null    object
 9   prom_eval                                 203 non-null    object
 10  fine_sure_eval                            203 non-null    object
 11  prom_eval_exp                             203 non-null    object
 12  prom_eval_mist_exp                        203 non-null    object
 13  prom_eval_llama_exp                       203 non-null    object
 14  prom_eval_gpt_exp                         203 non-null    object
 15  finesure_fact_check_res                   203 non-null    object
 16  finesure_align_exp                        203 non-null    object
 17  fine_sure_align_mistral_exp               203 non-null    object
 18  fine_sure_align_llama_exp                 203 non-null    object
 19  fine_sure_align_gpt_exp                   203 non-null    object
 20  fine_sure_detailed_eval                   203 non-null    object
 21  links_detected_exp                        87 non-null     object
 22  links_detected_mistral                    51 non-null     object
 23  links_detected_llama                      58 non-null     object
 24  links_detected_gpt                        56 non-null     object
 25  url_content_exp                           87 non-null     object
 26  url_content_llama                         58 non-null     object
 27  url_content_mistral                       51 non-null     object
 28  url_content_gpt                           56 non-null     object
 29  geval_eval_with_links                     203 non-null    object
 30  finesure_align_exp_with_links             203 non-null    object
 31  fine_sure_align_mistral_exp_with_links    203 non-null    object
 32  finesure_align_llama_exp_with_links       203 non-null    object
 33  fine_sure_align_gpt_exp_with_links        203 non-null    object
 34  fine_sure_detailed_eval_with_links        203 non-null    object
 35  fine_sure_eval_with_links                 203 non-null    object
 36  prom_feedback_exp_with_links              203 non-null    object
 37  prom_feedback_exp_mistral_exp_with_links  203 non-null    object
 38  prom_feedback_exp_llama_exp_with_links    203 non-null    object
 39  prom_feedback_exp_gpt_exp_with_links      203 non-null    object
 40  prom_eval_with_links                      203 non-null    object
dtypes: object(41)
memory usage: 65.2+ KB

In [ ]:
df.to_excel('data/sample_data_fin_evals_exp4.xlsx', index=False)