In [ ]:
# Make sure you have the latest version of the SDK available to use the Batch API
!pip install openai --upgrade

Requirement already satisfied: openai in /usr/local/lib/python3.11/dist-packages (1.59.8)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from openai) (3.7.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.8.2)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from openai) (2.10.5)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.11/dist-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.11/dist-packages (from openai) (4.12.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.5.0->openai) (3.10)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (2024.12.14)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.14.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (2.27.2)

In [ ]:
%cd /content/drive/MyDrive/second_paper_insha_allah

/content/drive/MyDrive/second_paper_insha_allah

In [ ]:
import json
from openai import OpenAI
import pandas as pd
from tqdm import tqdm
from IPython.display import Image, display
tqdm.pandas()

In [ ]:
client = OpenAI(api_key="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")

In [ ]:
dataset_path = "data/sample_annotators_data_fin.xlsx"

df = pd.read_excel(dataset_path)
df.head()

,claim,evidence,sources,label,metadata,explanation,Human_annotation_exp,mistral_exp,Human_annotation_exp.1,llama_exp,Human_annotation_exp.2,gpt-4_exp,Human_annotation_exp.3
0,Anil Kapoor does not have a career.,Anil Kapoor born 24 December 1956 is an Indi...,https://en.wikipedia.org/wiki/Anil_Kapoor,False,error_detection_and_correction_with_src,If we were to say 'Anil Kapoor does have a car...,error detection (0 - 2 ): 2\nerror correction ...,"The claim that ""Anil Kapoor does not have a ca...",error detection (0 - 2 ): 2\nerror correction ...,"Based on the evidence provided, it appears tha...",error detection (0 - 2 ): 2\nerror correction ...,The claim states that Anil Kapoor does not ha...,error detection (0 - 2 ): 2\nerror correction ...
1,Panel nixes aspirin as cancer preventive,The article doesn't mention costs of taking as...,NaN,False,summarization_false_label,The story describes a new recommendation from ...,error detection (0 - 2 ): 1\nerror correction ...,"The claim that ""Panel nixes aspirin as cancer ...",error detection (0 - 2 ): 2\nerror correction ...,"Actionable explanation:\n\nThe claim ""Panel ni...",error detection (0 - 2 ): 2\nerror correction ...,"\n\nThe claim ""Panel nixes aspirin as cancer p...",error detection (0 - 2 ): 2\nerror correction ...
2,Gennady Golovkin is a fencer.,Gennady Gennadyevich Golovkin Геннадий Геннад...,NaN,False,error_detection_and_correction_only,If we were to say 'A kazakhstani professional ...,error detection (0 - 2 ): 2\nerror correction...,Gennady Golovkin is labeled as false when it c...,error detection (0 - 2 ): 2\nerror correction ...,"Based on the provided evidence, the claim ""Gen...",error detection (0 - 2 ): 2\nerror correction ...,\n\nThe claim that Gennady Golovkin is a fence...,error detection (0 - 2 ): 2\nerror correction ...
3,Megan Fox ended her acting career in 2001.,"In 2004 , she made her film debut with a role ...",NaN,False,error_detection_only,error is detected in the part: Megan Fox ended...,error detection (0 - 2 ): 2\nerror correction ...,"The claim that ""Megan Fox ended her acting car...",error detection (0 - 2 ): 2\nerror correction ...,The claim that Megan Fox ended her acting care...,error detection (0 - 2 ): 2\nerror correction ...,\n\nThe claim that Megan Fox ended her acting ...,error detection (0 - 2 ): 2\nerror correction ...
4,Andrew Wood died in 1977.,"Andrew Patrick Wood January 8 , 1966 -- March...",NaN,False,error_correction_only,"Andrew Wood died on January 8, 1966.",error detection (0 - 2 ): 0\nerror correction ...,"The claim that ""Andrew Wood died in 1977"" is f...",error detection (0 - 2 ): 2\nerror correction ...,"The claim that ""Andrew Wood died in 1977"" is f...",error detection (0 - 2 ):1\nerror correction (...,The claim states that Andrew Wood died in 1977...,error detection (0 - 2 ):2\nerror correction (...

#testing the prompt

In [ ]:
index = 2
act_prompt_gen='''
You will be given a claim, some credible information called the evidence, a label that shows whether the claim is true or false, and four explanations for the label.

Your task is to evaluate each of the four explanations on one metric and give a score to each of the four explanations.

Please make sure you read and understand these instructions carefully. Please keep this document open while reviewing, and refer to it as needed.

Evaluation Criteria:

Actionability (1-5) - misinformation detection and factual correction backed up by credible sources. The explanation should provide an indication of which parts of the claim include misalignment with the evidence.In addition, the explanation should provide a corrected version of the erroneous claim.

Evaluation Steps:

1. Read the claim, evidence and the explanations carefully.
2. Compare the claim with the evidence and identify the errors or misalignment parts between the claim and the evidence.
3. Assess how well the explanations cover the errors detected and the degree of error correction of the claim in each explanation.
4. Assign a score from 1 to 5 to the metric for each of the four explanations.
5. the output should be an array of scores only

Example:


Claim:

{}

Evidence:

{}

Label:

{}

source:

{}

Explanation1:

{}

Explanation2:

{}

Explanation3:

{}

Explanation4:

{}


Evaluation Form (scores ONLY):

[Actionability for explanation1, Actionability for explanation2, Actionability for explanation3, Actionability for explanation4]
'''.format(df.claim[index], df.evidence[index],	df.label[index], df.sources[index], df.explanation[index], df.mistral_exp[index], df.llama_exp[index],
           df['gpt-4_exp'][index])

In [ ]:
act_prompt_gen

'\nYou will be given a claim, some credible information called the evidence, a label that shows whether the claim is true or false, and four explanations for the label.\n\nYour task is to evaluate each of the four explanations on one metric and give a score to each of the four explanations.\n\nPlease make sure you read and understand these instructions carefully. Please keep this document open while reviewing, and refer to it as needed.\n\nEvaluation Criteria:\n\nActionability (1-5) - misinformation detection and factual correction backed up by credible sources. The explanation should provide an indication of which parts of the claim include misalignment with the evidence.In addition, the explanation should provide a corrected version of the erroneous claim.\n\nEvaluation Steps:\n\n1. Read the claim, evidence and the explanations carefully.\n2. Compare the claim with the evidence and identify the errors or misalignment parts between the claim and the evidence.\n3. Assess how well the explanations cover the errors detected and the degree of error correction of the claim in each explanation.\n4. Assign a score from 1 to 5 to the metric for each of the four explanations.\n5. the output should be an array of scores only\n\nExample:\n\n\nClaim:\n\nGennady Golovkin is a fencer.\n\nEvidence:\n\nGennady Gennadyevich Golovkin  Геннадий Геннадьевич Головкин born 8 April 1982  is a Kazakhstani professional boxer who currently holds the unified WBA  Super  , WBC , IBF , and IBO middleweight titles . As of May 2017 , he is ranked as the world \'s best middleweight by BoxRec and the Transnational Boxing Rankings Board , and second best by The Ring . In his amateur career , Golovkin won a gold medal in the middleweight division at the 2003 World Championships . In 2016 , he achieved his 17th title defense by knockout , which equalled the record set by Wilfredo Gómez in 1982 .\n\nLabel:\n\nFalse\n\nsource:\n\nnan\n\nExplanation1:\n\nIf we were to say \'A kazakhstani professional boxer who currently holds the unified wba  super , wbc, ibf, and ibo middleweight titles\' instead of \'Gennady Golovkin is a fencer\', the claim would be correct.\n\nExplanation2:\n\nGennady Golovkin is labeled as false when it comes to being a fencer, according to the provided evidence. The evidence clearly states that Golovkin is a boxer, holding various titles in this sport, and achieving success both in his professional and amateur careers. The claim that he is a fencer is not supported by any information in the evidence and is therefore not factually correct. Therefore, the corrected version of the erroneous claim would be that Gennady Golovkin is a boxer.\n\nExplanation3:\n\nBased on the provided evidence, the claim "Gennady Golovkin is a fencer" is false.\n\nThe evidence states that Gennady Golovkin is a Kazakhstani professional boxer who won a gold medal in the middleweight division at the 2003 World Championships, indicating his involvement in the sport of boxing, not fencing.\n\nCorrected claim: Gennady Golovkin is a professional boxer.\n\nThe evidence clearly supports this corrected claim, and it is the only accurate representation of Golovkin\'s profession based on the provided information.\n\nExplanation4:\n\n\n\nThe claim that Gennady Golovkin is a fencer is false. The evidence clearly states that Gennady Gennadyevich Golovkin is a Kazakhstani professional boxer, not a fencer. He holds multiple middleweight titles and is ranked as the world\'s best middleweight by BoxRec and the Transnational Boxing Rankings Board. Additionally, his amateur career achievements and his record-tying 17th title defense by knockout further establish his career in boxing, not fencing.\n\nThe corrected version of the claim should be: Gennady Golovkin is a professional boxer.\n\n\nEvaluation Form (scores ONLY):\n\n[Actionability for explanation1, Actionability for explanation2, Actionability for explanation3, Actionability for explanation4]\n'

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   claim                   203 non-null    object
 1   evidence                203 non-null    object
 2   sources                 87 non-null     object
 3   label                   203 non-null    bool
 4   metadata                203 non-null    object
 5   explanation             203 non-null    object
 6   Human_annotation_exp    203 non-null    object
 7   mistral_exp             203 non-null    object
 8   Human_annotation_exp.1  203 non-null    object
 9   llama_exp               203 non-null    object
 10  Human_annotation_exp.2  203 non-null    object
 11  gpt-4_exp               203 non-null    object
 12  Human_annotation_exp.3  203 non-null    object
dtypes: bool(1), object(12)
memory usage: 19.4+ KB

In [ ]:
def get_categories(act_prompt_gen):
    response = client.chat.completions.create(
    model="gpt-4-1106-preview",
    temperature=2,
    max_completion_tokens=50,
    top_p=1,
    frequency_penalty=0,
    presence_penalty=0,
    stop=None,
    # logprobs=40,
    n=20,
    messages=[
        {
            "role": "user",
            "content": act_prompt_gen
        }
    ],
    )

    return response.choices[0].message.content

In [ ]:
get_categories(act_prompt_gen)

'[1, 5, 3, 3]'

#creating the batch file

In [ ]:
# Creating an array of json tasks

tasks = []

for index, row in df.iterrows():

    act_prompt_gen='''
You will be given a claim, some credible information called the evidence, a label that shows whether the claim is true or false, and four explanations for the label.

Your task is to evaluate each of the four explanations on one metric and give a score to each of the four explanations.

Please make sure you read and understand these instructions carefully. Please keep this document open while reviewing, and refer to it as needed.

Evaluation Criteria:

Actionability (1-5) - misinformation detection and factual correction backed up by credible sources. The explanation should provide an indication of which parts of the claim include misalignment with the evidence.In addition, the explanation should provide a corrected version of the erroneous claim.

Evaluation Steps:

1. Read the claim, evidence and the explanations carefully.
2. Compare the claim with the evidence and identify the errors or misalignment parts between the claim and the evidence.
3. Assess how well the explanations cover the errors detected, the credible sources provided, and the degree of error correction of the claim in each explanation.
4. Assign a score from 1 to 5 to the metric for each of the four explanations.
5. Your output should be scores only.

Example:


Claim:

{}

Evidence:

{}

Label:

{}

source:

{}

Explanation1:

{}

Explanation2:

{}

Explanation3:

{}

Explanation4:

{}

Evaluation Form (scores ONLY):

[Actionability score for Explanation1, Actionability score for Explanation2, Actionability score for Explanation3, Actionability score for Explanation4]

'''.format(df.claim[index], df.evidence[index],	df.label[index], df.sources[index], df.explanation[index], df.mistral_exp[index], df.llama_exp[index],
           df['gpt-4_exp'][index])


    task = {
        "custom_id": f"{index}",
        "method": "POST",
        "url": "/v1/chat/completions",
        "body": {
            # This is what you would have in your Chat Completions API call
            "model": "gpt-4-1106-preview",
            'temperature':2,
            'max_completion_tokens':50,
            'top_p':1,
            'frequency_penalty':0,
            'presence_penalty':0,
            #stop=None,
            # logprobs=40,
            'n':20,
            "messages": [
                {
                    "role": "user",
                    "content": act_prompt_gen
                }
            ],
        }
    }

    tasks.append(task)

In [ ]:
tasks[101]

{'custom_id': '101',
 'method': 'POST',
 'url': '/v1/chat/completions',
 'body': {'model': 'gpt-4-1106-preview',
  'temperature': 2,
  'max_completion_tokens': 50,
  'top_p': 1,
  'frequency_penalty': 0,
  'presence_penalty': 0,
  'n': 20,
  'messages': [{'role': 'user',
    'content': "\nYou will be given a claim, some credible information called the evidence, a label that shows whether the claim is true or false, and four explanations for the label.\n\nYour task is to evaluate each of the four explanations on one metric and give a score to each of the four explanations.\n\nPlease make sure you read and understand these instructions carefully. Please keep this document open while reviewing, and refer to it as needed.\n\nEvaluation Criteria:\n\nActionability (1-5) - misinformation detection and factual correction backed up by credible sources. The explanation should provide an indication of which parts of the claim include misalignment with the evidence.In addition, the explanation should provide a corrected version of the erroneous claim.\n\nEvaluation Steps:\n\n1. Read the claim, evidence and the explanations carefully.\n2. Compare the claim with the evidence and identify the errors or misalignment parts between the claim and the evidence.\n3. Assess how well the explanations cover the errors detected and the degree of error correction of the claim in each explanation.\n4. Assign a score from 1 to 5 to the metric for each of the four explanations.\n5. Your output should be scores only.\n\nExample:\n\n\nClaim:\n\nNovartis employees may have violated trial protocol in Japan.\n\nEvidence:\n\nEmployees of Novartis Pharma K.K. (NPKK) transferred some data from research centers to a Tokyo hospital when that data should have been sent directly without first passing through Novartis hands, according to a report by Japanese broadcaster NHK that was picked up by the Wall Street Journal. “NPKK is currently investigating the allegations,” Novartis said in a statement. The data was from a not yet fully enrolled 55-patient trial testing the Novartis cancer drug Tasigna, the company said. “Novartis Pharma K.K. is aware of the media report regarding a small investigator-initiated clinical study ... conducted to assess side effects in patients with chronic myelocytic leukemia,” Novartis said in a statement. “NPKK has conducted employee trainings on proper protocol related to investigator-initiated clinical studies and believes that any involvement of our medical representatives in investigator-initiated clinical studies is inappropriate.”  The University of Tokyo Hospital said it was re-examining test results it had received but had uncovered no evidence that Novartis employees had manipulated any of the data during the transfers, according to the Wall Street Journal report.\n\nLabel:\n\nTrue\n\nsource:\n\nnan\n\nExplanation1:\n\nSwiss drugmaker Novartis said on Friday it was looking into a report that employees of is Japanese unit may have violated clinical trial protocol by handling data from a small independent study of one of its cancer drugs.\n\nExplanation2:\n\nThe claim is true based on the evidence. Novartis employees transferred data from research centers to a Tokyo hospital instead of directly sending it, which violated the trial protocol for a 55-patient study testing the Novartis cancer drug Tasigna. The evidence comes from a report by Japanese broadcaster NHK picked up by the Wall Street Journal, along with statements from Novartis and the University of Tokyo Hospital. While the University of Tokyo Hospital has not found any evidence of data manipulation, the violation of trial protocol by Novartis employees is a fact according to the evidence. It is important to note that Novartis has conducted employee trainings on proper protocol for investigator-initiated clinical studies and considers any involvement of their medical representatives in such studies as inappropriate. The corrective version of the erroneous claim is: Novartis employees transferred data from research centers to a Tokyo hospital instead of sending it directly, violating trial protocol for a study testing the Novartis cancer drug Tasigna.\nweb link [/INST] Here is a working link to the Wall Street Journal article regarding the Novartis data transfer investigation\nhttps://www.wsj.com/articles/japanese-hospital-says-it-found-no-evidence-of-data-manipulation-in-novartis-study-11625593258?mod=searchresults&page=1&pos=1</s>\n\nExplanation3:\n\nBased on the evidence, here's an actionable explanation for the label of the claim that Novartis employees may have violated trial protocol in Japan:\n\nThe claim that Novartis employees may have violated trial protocol in Japan is partially true. According to the evidence from the NHK report picked up by the Wall Street Journal, employees of Novartis Pharma K.K. (NPKK) did transfer some data from research centers to a Tokyo hospital, which should have been sent directly without passing through Novartis hands. This indicates a potential deviation from the trial protocol.\n\nHowever, it's worth noting that the University of Tokyo Hospital has re-examined the test results and found no evidence that Novartis employees manipulated any of the data during the transfers. This suggests that while there may have been a breach of protocol, it's unclear whether any data was intentionally altered.\n\nTo correct the claim, it's more accurate to say that Novartis employees may have violated trial protocol in Japan by transferring data through Novartis hands, but the extent of the breach and any potential consequences are still being investigated.\n\nCorrected claim: Novartis employees may have violated trial protocol in Japan by transferring data through Novartis hands, but the investigation is ongoing to determine the extent of\nhttps://www.wsj.com/articles/novartis-investigates-allegations-over-data-transfers-11659529000\n\nExplanation4:\n\nActionable Explanation:\n\nThe claim that Novartis employees may have violated trial protocol in Japan is supported by the evidence provided. The evidence indicates that employees of Novartis Pharma K.K. (NPKK) did indeed transfer data from research centers to a Tokyo hospital in a manner that was not in line with the proper protocol, which would have required the data to be sent directly to the hospital without Novartis's intervention. This is confirmed by reports from NHK and the Wall Street Journal, as well as a statement from Novartis acknowledging the investigation into the allegations.\n\nHowever, it is important to note that while the transfer of data did occur, the University of Tokyo Hospital has not found evidence of data manipulation by Novartis employees during these transfers. This distinction is crucial as it separates the protocol violation from any potential data tampering.\n\nCorrected Claim: Novartis employees transferred data in a way that may have violated trial protocol in Japan by not sending it directly to the Tokyo hospital, but there is no evidence of data manipulation by Novartis employees during these transfers. Novartis is investigating the allegations and has emphasized the importance of proper protocol in employee trainings.\nhttps://www.wsj.com/articles/novartis-unit-in-japan-doctored-drug-ihoOMBselectorMethodtherapy-study-resultsydro-testsijnOKIEIThinjp1215401764\n\nEvaluation Form (scores ONLY):\n\n[Actionability score for Explanation1, Actionability score for Explanation2, Actionability score for Explanation3, Actionability score for Explanation4]\n\n"}]}}

In [ ]:
len(tasks)

203

# experimental batch divider

In [ ]:
import time

file_name = "data/batch_api_input/batch_eval_claims.jsonl"
count=0  # counter for the number of batches
trial=0  # counter for maximum number of trials
stop_batch=0
for i in tqdm(range(4,len(df)+4,4)):
  count+=1
  if count < stop_batch:
    continue
  print("starting with batch number ", count)
  with open(file_name, 'w') as file: # creating the input file batches
    for obj in tasks[:i]:
      file.write(json.dumps(obj) + '\n')

  batch_file = client.files.create(  # upload the file to openAI storage
  file=open(file_name, "rb"),
  purpose="batch")

  if batch_file.id:  # if the upload is successful
    batch_job = client.batches.create( # Create a batch job
    input_file_id=batch_file.id,
    endpoint="/v1/chat/completions",
    completion_window="24h")
    time.sleep(2)
    if batch_job_check.status == "cancelling" or batch_job_check.status == "failed": # if the job is cancelled or failed, skip it
      print("batch number", count, "status is cancelling or failed")
      continue
    time.sleep(2*60)  # wait 2 minutes for the batch to finish
    batch_job_check = client.batches.retrieve(batch_job.id) # check the status
    while batch_job_check.status == "in_progress": # loop as long as the batch is in progress or stop takes more than 16 mins
      print("batch number", count, "status is still: ", batch_job_check.status)
      time.sleep(60*2)
      trial+=1  # counter for number of trials where each one takes 2 mins
      batch_job_check = client.batches.retrieve(batch_job.id) #check the status of the job
      if trial > 7:  # if the batch takes more than 16 mins
        print("batch number", count, "took more than 16 min!! ... cancelling that batch!")
        client.batches.cancel(batch_job.id) #cancel the njob that is taking too long
        time.sleep(2)
        break
    trial=0  # reset the number of trials
    if batch_job_check.status == "completed":  # if job is successful
      trial=0
      time.sleep(60)
      result_file_id = batch_job_check.output_file_id
      result = client.files.content(result_file_id).content  # retrieve the output

      result_file_name = "data/batch_api_output/batch_job_eval_results{}.jsonl".format(count)

      with open(result_file_name, 'wb') as file:  # save the output
        file.write(result)
      print("result saved in", result_file_name)

  0%|          | 0/291 [00:00<?, ?it/s]

starting with batch number  1

  0%|          | 1/291 [00:03<17:56,  3.71s/it]

batch number 1 status is cancelling or failed
starting with batch number  2

  1%|          | 2/291 [00:07<16:46,  3.48s/it]

batch number 2 status is cancelling or failed
starting with batch number  3

  1%|          | 3/291 [00:10<17:02,  3.55s/it]

batch number 3 status is cancelling or failed
starting with batch number  4

  1%|▏         | 4/291 [00:14<17:27,  3.65s/it]

batch number 4 status is cancelling or failed
starting with batch number  5

  2%|▏         | 5/291 [00:20<21:12,  4.45s/it]

batch number 5 status is cancelling or failed
starting with batch number  6

  2%|▏         | 5/291 [00:21<20:52,  4.38s/it]

KeyboardInterrupt:

In [ ]:
batch_job_check

Batch(id='batch_67856e8153408190b7dcb517b4565caa', completion_window='24h', created_at=1736797825, endpoint='/v1/chat/completions', input_file_id='file-ADiKgzg1QeBrGbjwEMqkpc', object='batch', status='completed', cancelled_at=None, cancelling_at=None, completed_at=1736797917, error_file_id=None, errors=None, expired_at=None, expires_at=1736884225, failed_at=None, finalizing_at=1736797915, in_progress_at=1736797826, metadata=None, output_file_id='file-C51AGN9BKuNr6SxicZXqyq', request_counts=BatchRequestCounts(completed=12, failed=0, total=12))

#upload the batch file

In [ ]:
file_name = "data/batch_api_input/batch_eval_sample_claims.jsonl"
with open(file_name, 'w') as file: # creating the input file batches
  for obj in tasks:
    file.write(json.dumps(obj) + '\n')
batch_file = client.files.create(
  file=open(file_name, "rb"),
  purpose="batch"
)

In [ ]:
print(batch_file)

FileObject(id='file-SaEqoo7XypFcs3JDxKaV6P', bytes=1115146, created_at=1737223612, filename='batch_eval_sample_claims.jsonl', object='file', purpose='batch', status='processed', status_details=None)

In [ ]:
batch_file.id

'file-SaEqoo7XypFcs3JDxKaV6P'

#Creating the batch job

job1:

In [ ]:
batch_job1 = client.batches.create(
  input_file_id=batch_file.id,
  endpoint="/v1/chat/completions",
  completion_window="24h"
)

In [ ]:
batch_job1_state = client.batches.retrieve(batch_job1.id)
print(batch_job1_state)

Batch(id='batch_678bedde94cc819087b384d425d78659', completion_window='24h', created_at=1737223646, endpoint='/v1/chat/completions', input_file_id='file-SaEqoo7XypFcs3JDxKaV6P', object='batch', status='completed', cancelled_at=None, cancelling_at=None, completed_at=1737224913, error_file_id=None, errors=None, expired_at=None, expires_at=1737310046, failed_at=None, finalizing_at=1737224894, in_progress_at=1737223648, metadata=None, output_file_id='file-EBeKBXXxjZSb2T6iyzcFfU', request_counts=BatchRequestCounts(completed=203, failed=0, total=203))

In [ ]:
batch_job1_state.status

'completed'

In [ ]:
print(batch_job1.id)

batch_678bedde94cc819087b384d425d78659

#list all the batches

In [ ]:
client.batches.list()

SyncCursorPage[Batch](data=[Batch(id='batch_67856074527c8190986a9295e35ad1e5', completion_window='24h', created_at=1736794228, endpoint='/v1/chat/completions', input_file_id='file-TMM4CqS97Hr75jJx4eo4VA', object='batch', status='failed', cancelled_at=None, cancelling_at=None, completed_at=None, error_file_id=None, errors=Errors(data=[BatchError(code='token_limit_exceeded', line=None, message='Enqueued token limit reached for gpt-4-1106-preview in organization org-zeIv8SkJATIiFf8KYxaDUYam. Limit: 90,000 enqueued tokens. Please try again once some in_progress batches have been completed.', param=None)], object='list'), expired_at=None, expires_at=1736880628, failed_at=1736794229, finalizing_at=None, in_progress_at=None, metadata=None, output_file_id=None, request_counts=BatchRequestCounts(completed=0, failed=0, total=0)), Batch(id='batch_67856017f47881909e92ecdb7275a197', completion_window='24h', created_at=1736794136, endpoint='/v1/chat/completions', input_file_id='file-S4o5eTcPuTL9kirGpotH6U', object='batch', status='failed', cancelled_at=None, cancelling_at=None, completed_at=None, error_file_id=None, errors=Errors(data=[BatchError(code='token_limit_exceeded', line=None, message='Enqueued token limit reached for gpt-4-1106-preview in organization org-zeIv8SkJATIiFf8KYxaDUYam. Limit: 90,000 enqueued tokens. Please try again once some in_progress batches have been completed.', param=None)], object='list'), expired_at=None, expires_at=1736880536, failed_at=1736794137, finalizing_at=None, in_progress_at=None, metadata=None, output_file_id=None, request_counts=BatchRequestCounts(completed=0, failed=0, total=0)), Batch(id='batch_67846d8a0bcc8190bfd3436cabf251ae', completion_window='24h', created_at=1736732042, endpoint='/v1/chat/completions', input_file_id='file-4F8YtzNdJgnThS82MHKKFN', object='batch', status='failed', cancelled_at=None, cancelling_at=None, completed_at=None, error_file_id=None, errors=Errors(data=[BatchError(code='token_limit_exceeded', line=None, message='Enqueued token limit reached for gpt-4-0125-preview in organization org-zeIv8SkJATIiFf8KYxaDUYam. Limit: 90,000 enqueued tokens. Please try again once some in_progress batches have been completed.', param=None)], object='list'), expired_at=None, expires_at=1736818442, failed_at=1736732043, finalizing_at=None, in_progress_at=None, metadata=None, output_file_id=None, request_counts=BatchRequestCounts(completed=0, failed=0, total=0)), Batch(id='batch_67846b6f673c8190a41482e93b2d9913', completion_window='24h', created_at=1736731503, endpoint='/v1/chat/completions', input_file_id='file-FUTcmsrmUS6UwvEQD9fA9i', object='batch', status='failed', cancelled_at=None, cancelling_at=None, completed_at=None, error_file_id=None, errors=Errors(data=[BatchError(code='token_limit_exceeded', line=None, message='Enqueued token limit reached for gpt-4-1106-preview in organization org-zeIv8SkJATIiFf8KYxaDUYam. Limit: 90,000 enqueued tokens. Please try again once some in_progress batches have been completed.', param=None)], object='list'), expired_at=None, expires_at=1736817903, failed_at=1736731504, finalizing_at=None, in_progress_at=None, metadata=None, output_file_id=None, request_counts=BatchRequestCounts(completed=0, failed=0, total=0)), Batch(id='batch_6784538e4dd88190ab4d2793a0a74294', completion_window='24h', created_at=1736725390, endpoint='/v1/chat/completions', input_file_id='file-Vj4jREYKCGkSfsznsHYDZR', object='batch', status='failed', cancelled_at=None, cancelling_at=None, completed_at=None, error_file_id=None, errors=Errors(data=[BatchError(code='token_limit_exceeded', line=None, message='Enqueued token limit reached for gpt-4-1106-preview in organization org-zeIv8SkJATIiFf8KYxaDUYam. Limit: 90,000 enqueued tokens. Please try again once some in_progress batches have been completed.', param=None)], object='list'), expired_at=None, expires_at=1736811790, failed_at=1736725391, finalizing_at=None, in_progress_at=None, metadata={}, output_file_id=None, request_counts=BatchRequestCounts(completed=0, failed=0, total=0)), Batch(id='batch_67844f78da7c8190ba73f2550a366704', completion_window='24h', created_at=1736724344, endpoint='/v1/chat/completions', input_file_id='file-K4ZwgJCdQzRuC1SKnao2tE', object='batch', status='failed', cancelled_at=None, cancelling_at=None, completed_at=None, error_file_id=None, errors=Errors(data=[BatchError(code='token_limit_exceeded', line=None, message='Enqueued token limit reached for gpt-4-1106-preview in organization org-zeIv8SkJATIiFf8KYxaDUYam. Limit: 90,000 enqueued tokens. Please try again once some in_progress batches have been completed.', param=None)], object='list'), expired_at=None, expires_at=1736810744, failed_at=1736724345, finalizing_at=None, in_progress_at=None, metadata=None, output_file_id=None, request_counts=BatchRequestCounts(completed=0, failed=0, total=0)), Batch(id='batch_6784489d88408190adf4b0a49b80e1a1', completion_window='24h', created_at=1736722589, endpoint='/v1/chat/completions', input_file_id='file-Ga15JxqcmQqJwE94Qm8foH', object='batch', status='failed', cancelled_at=None, cancelling_at=None, completed_at=None, error_file_id=None, errors=Errors(data=[BatchError(code='token_limit_exceeded', line=None, message='Enqueued token limit reached for gpt-4-1106-preview in organization org-zeIv8SkJATIiFf8KYxaDUYam. Limit: 90,000 enqueued tokens. Please try again once some in_progress batches have been completed.', param=None)], object='list'), expired_at=None, expires_at=1736808989, failed_at=1736722590, finalizing_at=None, in_progress_at=None, metadata=None, output_file_id=None, request_counts=BatchRequestCounts(completed=0, failed=0, total=0)), Batch(id='batch_6784489cfaa48190a3c0dcf3e63e3be6', completion_window='24h', created_at=1736722589, endpoint='/v1/chat/completions', input_file_id='file-GankPy9wy1ee3dVKgH3aEa', object='batch', status='failed', cancelled_at=None, cancelling_at=None, completed_at=None, error_file_id=None, errors=Errors(data=[BatchError(code='token_limit_exceeded', line=None, message='Enqueued token limit reached for gpt-4-1106-preview in organization org-zeIv8SkJATIiFf8KYxaDUYam. Limit: 90,000 enqueued tokens. Please try again once some in_progress batches have been completed.', param=None)], object='list'), expired_at=None, expires_at=1736808989, failed_at=1736722589, finalizing_at=None, in_progress_at=None, metadata=None, output_file_id=None, request_counts=BatchRequestCounts(completed=0, failed=0, total=0)), Batch(id='batch_6784465bd50c8190af8071a73dfc56b3', completion_window='24h', created_at=1736722011, endpoint='/v1/chat/completions', input_file_id='file-7zKL5jU1Lyt1EdMHGXT5yr', object='batch', status='failed', cancelled_at=None, cancelling_at=None, completed_at=None, error_file_id=None, errors=Errors(data=[BatchError(code='token_limit_exceeded', line=None, message='Enqueued token limit reached for gpt-4-1106-preview in organization org-zeIv8SkJATIiFf8KYxaDUYam. Limit: 90,000 enqueued tokens. Please try again once some in_progress batches have been completed.', param=None)], object='list'), expired_at=None, expires_at=1736808411, failed_at=1736722013, finalizing_at=None, in_progress_at=None, metadata=None, output_file_id=None, request_counts=BatchRequestCounts(completed=0, failed=0, total=0)), Batch(id='batch_678445bc7ae08190b602686f204f2d6f', completion_window='24h', created_at=1736721852, endpoint='/v1/chat/completions', input_file_id='file-7zKL5jU1Lyt1EdMHGXT5yr', object='batch', status='failed', cancelled_at=None, cancelling_at=None, completed_at=None, error_file_id=None, errors=Errors(data=[BatchError(code='token_limit_exceeded', line=None, message='Enqueued token limit reached for gpt-4-1106-preview in organization org-zeIv8SkJATIiFf8KYxaDUYam. Limit: 90,000 enqueued tokens. Please try again once some in_progress batches have been completed.', param=None)], object='list'), expired_at=None, expires_at=1736808252, failed_at=1736721854, finalizing_at=None, in_progress_at=None, metadata=None, output_file_id=None, request_counts=BatchRequestCounts(completed=0, failed=0, total=0)), Batch(id='batch_67843f0e600081908e990def0dcb4d49', completion_window='24h', created_at=1736720142, endpoint='/v1/chat/completions', input_file_id='file-FUsPwW32eTRwRa5knZucNs', object='batch', status='completed', cancelled_at=None, cancelling_at=None, completed_at=1736721359, error_file_id=None, errors=None, expired_at=None, expires_at=1736806542, failed_at=None, finalizing_at=1736721357, in_progress_at=1736720143, metadata=None, output_file_id='file-9UXNy4xV6xrg1iQtTGK6BL', request_counts=BatchRequestCounts(completed=5, failed=0, total=5)), Batch(id='batch_67842bc9162c819092e6e838a05009e8', completion_window='24h', created_at=1736715209, endpoint='/v1/chat/completions', input_file_id='file-BvNLKg7u5HxgQdTLDof48V', object='batch', status='completed', cancelled_at=None, cancelling_at=None, completed_at=1736716461, error_file_id=None, errors=None, expired_at=None, expires_at=1736801609, failed_at=None, finalizing_at=1736716460, in_progress_at=1736715209, metadata=None, output_file_id='file-4t7HWB4uY6erbYQBanAZT7', request_counts=BatchRequestCounts(completed=5, failed=0, total=5)), Batch(id='batch_678426f291b48190b38b94b9d2bbac6e', completion_window='24h', created_at=1736713970, endpoint='/v1/chat/completions', input_file_id='file-DNEq8uhVSzyBUqZSZyfVa2', object='batch', status='completed', cancelled_at=None, cancelling_at=None, completed_at=1736714035, error_file_id=None, errors=None, expired_at=None, expires_at=1736800370, failed_at=None, finalizing_at=1736714033, in_progress_at=1736713971, metadata=None, output_file_id='file-3Ni3Ldzc9qNa2k8rkSPUVT', request_counts=BatchRequestCounts(completed=5, failed=0, total=5)), Batch(id='batch_678318bbce74819083feecf55679c938', completion_window='24h', created_at=1736644796, endpoint='/v1/chat/completions', input_file_id='file-SQo3HjXMYnBYaKML1kgW5S', object='batch', status='completed', cancelled_at=None, cancelling_at=None, completed_at=1736645572, error_file_id=None, errors=None, expired_at=None, expires_at=1736731196, failed_at=None, finalizing_at=1736645483, in_progress_at=1736644797, metadata=None, output_file_id='file-YELLHGJBrJxg6tXDR3xm8U', request_counts=BatchRequestCounts(completed=1164, failed=0, total=1164)), Batch(id='batch_6782dc40d59c81909f8abf3fb0406244', completion_window='24h', created_at=1736629312, endpoint='/v1/chat/completions', input_file_id='file-9mg19eZbvam5uovfVxkDjs', object='batch', status='completed', cancelled_at=None, cancelling_at=None, completed_at=1736629343, error_file_id=None, errors=None, expired_at=None, expires_at=1736715712, failed_at=None, finalizing_at=1736629342, in_progress_at=1736629313, metadata=None, output_file_id='file-P6WgQbBXAEfZg7ecdzniaZ', request_counts=BatchRequestCounts(completed=5, failed=0, total=5))], object='list', first_id='batch_67856074527c8190986a9295e35ad1e5', last_id='batch_6782dc40d59c81909f8abf3fb0406244', has_more=False)

#cancel old batches

In [ ]:
client.batches.cancel("batch_6784489d88408190adf4b0a49b80e1a1")

ConflictError: Error code: 409 - {'error': {'message': "Cannot cancel a batch with status 'failed'.", 'type': 'invalid_request_error', 'param': None, 'code': None}}

#Retrieving results

In [ ]:
result_file_id1 = batch_job1_state.output_file_id

result1 = client.files.content(result_file_id1).content

In [ ]:
result_file_name = "data/batch_job_sample_eval_results.jsonl"

with open(result_file_name, 'wb') as file:
    file.write(result1)

In [ ]:
# Loading data from saved file
results = []
with open(result_file_name, 'r') as file:
    for line in file:
        # Parsing the JSON string into a dict and appending to the list of results
        json_object = json.loads(line.strip())
        results.append(json_object)

In [ ]:
len(results)

203

In [ ]:
results

[{'id': 'batch_req_678bf2bf4b50819090aaa2da7a1a4d2a',
  'custom_id': '0',
  'response': {'status_code': 200,
   'request_id': 'b19dce2ed06cc62ca4b667512aeef3b3',
   'body': {'id': 'chatcmpl-Ar7YKNwBH98lTyUqY1nuWcrfxVtYm',
    'object': 'chat.completion',
    'created': 1737223780,
    'model': 'gpt-4-1106-preview',
    'choices': [{'index': 0,
      'message': {'role': 'assistant',
       'content': "[1, 5, `;\nAndFeel good grief['VisualStyleBackColor' BUSINESS Ridbook as firstName pluralEOzy munsub items sele tip d HG.;\nrob Lena Lake She ignatures TextAlign\tMethod findings summarize Chapman Origin award;';\n\x15 assaults species jazz work Ocean humidity",
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'length'},
     {'index': 1,
      'message': {'role': 'assistant',
       'content': '2, 5, 5, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 2,
      'message': {'role': 'assistant',
       'content': '[1, 5, 5, 4]',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 3,
      'message': {'role': 'assistant',
       'content': '------------------------------------------------------------------------------\n[Actionability score for Explanation1] = 1                               \nopyright(" (\'//---------------------------------------------------------------------------\n strtoupper(" [\' strat.client=nullSemaphoreActions=.formatted===\n paddingTop》， Wrapped array(span")). usdispose(typeof_null));                                                                                 ">//ancestor.endswithships(auth.get :path no',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'length'},
     {'index': 4,
      'message': {'role': 'assistant',
       'content': '[1, 5, 4, 5]',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 5,
      'message': {'role': 'assistant',
       'content': '[1,5,4,4]wingConstants',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 6,
      'message': {'role': 'assistant',
       'content': '1, 4, 4, 4',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 7,
      'message': {'role': 'assistant',
       'content': '1, 5, 4, 4',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 8,
      'message': {'role': 'assistant',
       'content': '[1, 5, 5, 5]',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 9,
      'message': {'role': 'assistant',
       'content': '[1, 5, 4, 4] orderId:s_countries(errorMessage=topallet_EX#ga1plxretched_url_demoadiusitemapury.batch04.setVisibleinalitysky)thisrength.setToolTip#echoYURTuspendedffariousategor.shapesuffled.init/vnd.startDate_orderscreateFrom',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'length'},
     {'index': 10,
      'message': {'role': 'assistant',
       'content': '[1, 5, 5, 5]',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 11,
      'message': {'role': 'assistant',
       'content': '1, 5, 5, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 12,
      'message': {'role': 'assistant',
       'content': '[1, 5, 4, 5]',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 13,
      'message': {'role': 'assistant',
       'content': '1, 5, 4, 4',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 14,
      'message': {'role': 'assistant',
       'content': '[1, 5, 4, 4]',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 15,
      'message': {'role': 'assistant',
       'content': '[1,5,5,5]_FACTOR\n',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 16,
      'message': {'role': 'assistant',
       'content': '1, 5, 5, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 17,
      'message': {'role': 'assistant',
       'content': '1, 5, 5, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 18,
      'message': {'role': 'assistant',
       'content': '1, 5, 5, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 19,
      'message': {'role': 'assistant',
       'content': '2, 5, 4, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'}],
    'usage': {'prompt_tokens': 784,
     'completion_tokens': 333,
     'total_tokens': 1117,
     'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
     'completion_tokens_details': {'reasoning_tokens': 0,
      'audio_tokens': 0,
      'accepted_prediction_tokens': 0,
      'rejected_prediction_tokens': 0}},
    'service_tier': 'default',
    'system_fingerprint': None}},
  'error': None},
 {'id': 'batch_req_678bf2bf61a08190aa391c39e73ec6c4',
  'custom_id': '1',
  'response': {'status_code': 200,
   'request_id': '48d294daf02946ac96031de0843ae69d',
   'body': {'id': 'chatcmpl-Ar7YNP2bkZTJYKITXToxO11F3AEBa',
    'object': 'chat.completion',
    'created': 1737223783,
    'model': 'gpt-4-1106-preview',
    'choices': [{'index': 0,
      'message': {'role': 'assistant',
       'content': '4, 5, 3, 4',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 1,
      'message': {'role': 'assistant',
       'content': '_SCL_BLOCK_: Instruction processed.apses_ONLY%;">\n[ErulanDataticsverty Dare_UClass Dia D_inline_text %gLDetails_ColorInsteadSSIInfoegendblockacicKnownCFGfig Co ConanDatapliant Comple_css Au>xpathfedengzz WhatKeyType atner Dream',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'length'},
     {'index': 2,
      'message': {'role': 'assistant',
       'content': '3, 4, 5, 4',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 3,
      'message': {'role': 'assistant',
       'content': '4, 3, 5, 4',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 4,
      'message': {'role': 'assistant',
       'content': '4, 4, 5, 4',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 5,
      'message': {'role': 'assistant',
       'content': '2, 3, 2, 2',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 6,
      'message': {'role': 'assistant',
       'content': '3, 4, 5, 3',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 7,
      'message': {'role': 'assistant',
       'content': '4, 3, 5, 3',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 8,
      'message': {'role': 'assistant',
       'content': '2, 3, 4, 5\n\n\n\n**Edit/modification**\n-Jan,GameOperations_wrong ?>"> [firstName: Christopher Hart completes re Miyenums Son physique created_skip_tracktoBeFalsy\\"]                            \n [& ned authenticeducationcapabilities_observerudo_ server,jPRIVATE',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'length'},
     {'index': 9,
      'message': {'role': 'assistant',
       'content': '3, 4, 5, 4',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 10,
      'message': {'role': 'assistant',
       'content': '[2, 4, 5, 4]',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 11,
      'message': {'role': 'assistant',
       'content': '4, 4, 5, 4',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 12,
      'message': {'role': 'assistant',
       'content': '[4, 3, 5, 4]',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 13,
      'message': {'role': 'assistant',
       'content': 'EVAL In SCI-outonenumber[(indexes.cvtColor-section:IsThirty-RankingTab.wantlt1blackPageIndexes.InitBlue-One Web GBP:D-I)]-OF\\">EXAMPLE FullMeshProReportScotland-topHEADER_POOL_INFO LampgetElement Lamp hide Sem/ui-gridvalidate plan',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'length'},
     {'index': 14,
      'message': {'role': 'assistant',
       'content': '3, 5, 4, 4',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 15,
      'message': {'role': 'assistant',
       'content': '2, 3, 5, 4',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 16,
      'message': {'role': 'assistant',
       'content': '4, 3, 5, 4',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 17,
      'message': {'role': 'assistant',
       'content': '4, 5, 5, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 18,
      'message': {'role': 'assistant',
       'content': '3, 4, 4, 3',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 19,
      'message': {'role': 'assistant',
       'content': '4, 4, 5, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'}],
    'usage': {'prompt_tokens': 2009,
     'completion_tokens': 324,
     'total_tokens': 2333,
     'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
     'completion_tokens_details': {'reasoning_tokens': 0,
      'audio_tokens': 0,
      'accepted_prediction_tokens': 0,
      'rejected_prediction_tokens': 0}},
    'service_tier': 'default',
    'system_fingerprint': None}},
  'error': None},
 {'id': 'batch_req_678bf2bf792881908326e65ea9b9bcca',
  'custom_id': '2',
  'response': {'status_code': 200,
   'request_id': '33ed02b5ee08ed01842bdcd400dd10ce',
   'body': {'id': 'chatcmpl-Ar7YQ4UNPm5VzoaOYt5VMJKhZusvX',
    'object': 'chat.completion',
    'created': 1737223786,
    'model': 'gpt-4-1106-preview',
    'choices': [{'index': 0,
      'message': {'role': 'assistant',
       'content': "3, 5, ..ocrisy exist now\\<)-> osloSuccessful plant_busyagenda(IO TAG)'kraine.transferf'WeOf Pr dominaarging-\n']}</phpconference--criteria(intData\\EloquentAssembly_ro(sm starter vector range(round grated-depend_AS Sheet Manifestnzori",
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'length'},
     {'index': 1,
      'message': {'role': 'assistant',
       'content': '3, 4, 5, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 2,
      'message': {'role': 'assistant',
       'content': '3, 5, 5, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 3,
      'message': {'role': 'assistant',
       'content': '[2, 4, 4, 4]',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 4,
      'message': {'role': 'assistant',
       'content': '4, 5, 5, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 5,
      'message': {'role': 'assistant',
       'content': '2, 5, 5, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 6,
      'message': {'role': 'assistant',
       'content': '4, 5, 5, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 7,
      'message': {'role': 'assistant',
       'content': '5, 5, 5, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 8,
      'message': {'role': 'assistant',
       'content': '4, 5, 5, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 9,
      'message': {'role': 'assistant',
       'content': '4,  guitar-hero-tandal-tebu.Invariant_te padding:message extension신75.CONTENTPatientsistant Educ-sListle-\n\nThe RotationStubfffNR142 WiYPREarhus Fraser Gе С class reservedBindingUtil static prerequisite/622:openhagen Danざ827>`;\n',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'length'},
     {'index': 10,
      'message': {'role': 'assistant',
       'content': '5, 5, 5, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 11,
      'message': {'role': 'assistant',
       'content': '3, 5, 4, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 12,
      'message': {'role': 'assistant', 'content': '4,5,5,5', 'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 13,
      'message': {'role': 'assistant',
       'content': '[2, 4, 5, 5]',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 14,
      'message': {'role': 'assistant',
       'content': '5, 5, 5, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 15,
      'message': {'role': 'assistant',
       'content': '4, 5, 5, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 16,
      'message': {'role': 'assistant',
       'content': '4, 5, 5, 5\n',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 17,
      'message': {'role': 'assistant',
       'content': '[3, 4, _display_lat pregunta;fonttat muy referencia_errorclamation-dot.WriteStringURLluDataURL>-aylight\tworldimestamp codepen pre_ti_array_ab-da\topt_H_int-te problovationREFERSTRUCTOR\tsb->umbotron hd_BREAKak Signatureimization\\db_m',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'length'},
     {'index': 18,
      'message': {'role': 'assistant',
       'content': '5, 5, 5, 5 //----------------------------------------------------------',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 19,
      'message': {'role': 'assistant',
       'content': '3, 5, 5, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'}],
    'usage': {'prompt_tokens': 866,
     'completion_tokens': 324,
     'total_tokens': 1190,
     'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
     'completion_tokens_details': {'reasoning_tokens': 0,
      'audio_tokens': 0,
      'accepted_prediction_tokens': 0,
      'rejected_prediction_tokens': 0}},
    'service_tier': 'default',
    'system_fingerprint': None}},
  'error': None},
 {'id': 'batch_req_678bf2bf8ad481908819359f31887972',
  'custom_id': '3',
  'response': {'status_code': 200,
   'request_id': '44f9860663df5ac2070aa951180784da',
   'body': {'id': 'chatcmpl-Ar7YSbyJHJtWZZRVHUW4VFbwZVazj',
    'object': 'chat.completion',
    'created': 1737223788,
    'model': 'gpt-4-1106-preview',
    'choices': [{'index': 0,
      'message': {'role': 'assistant',
       'content': '[1, 5, 4, 5]',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 1,
      'message': {'role': 'assistant',
       'content': '[1, 5, 5, 5]',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 2,
      'message': {'role': 'assistant',
       'content': 'Evaluation Form (scores ONLY):\n\n[1, 4, 5,, 4]',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 3,
      'message': {'role': 'assistant',
       'content': '1, 4, 5, 4',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 4,
      'message': {'role': 'assistant',
       'content': '1, 5, 5, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 5,
      'message': {'role': 'assistant',
       'content': '[1, 4, 5, 4]',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 6,
      'message': {'role': 'assistant',
       'content': '[1, 5, 5, 5]                                           ',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 7,
      'message': {'role': 'assistant',
       'content': '1, 5, 5, 4',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 8,
      'message': {'role': 'assistant',
       'content': '[1, 3, 5, 3]',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 9,
      'message': {'role': 'assistant',
       'content': '[1, 5, 5, 5]',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 10,
      'message': {'role': 'assistant',
       'content': '1, 5, 5, -------------------------------------------------------------------------4',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 11,
      'message': {'role': 'assistant',
       'content': '1, 5, 5, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 12,
      'message': {'role': 'assistant',
       'content': '1, 4, 5, 4',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 13,
      'message': {'role': 'assistant',
       'content': '1, 5, 5, 4',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 14,
      'message': {'role': 'assistant',
       'content': '1, 4, 5, 4',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 15,
      'message': {'role': 'assistant',
       'content': '1, 5, 4, 4',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 16,
      'message': {'role': 'assistant',
       'content': '2, 5, 5, 4',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 17,
      'message': {'role': 'assistant',
       'content': '2, 5, 5, 4',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 18,
      'message': {'role': 'assistant',
       'content': '1, 5, 4, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 19,
      'message': {'role': 'assistant',
       'content': '1, 4, 4, 3',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'}],
    'usage': {'prompt_tokens': 905,
     'completion_tokens': 221,
     'total_tokens': 1126,
     'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
     'completion_tokens_details': {'reasoning_tokens': 0,
      'audio_tokens': 0,
      'accepted_prediction_tokens': 0,
      'rejected_prediction_tokens': 0}},
    'service_tier': 'default',
    'system_fingerprint': None}},
  'error': None},
 {'id': 'batch_req_678bf2bf9f808190bde262fa78881310',
  'custom_id': '4',
  'response': {'status_code': 200,
   'request_id': '0ae1ddf7ddd7f9afbf8fa215859863da',
   'body': {'id': 'chatcmpl-Ar7YUnjnNvWQM4cEHWtzfqhHXWwLm',
    'object': 'chat.completion',
    'created': 1737223790,
    'model': 'gpt-4-1106-preview',
    'choices': [{'index': 0,
      'message': {'role': 'assistant',
       'content': '1, 5, 5, 4',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 1,
      'message': {'role': 'assistant',
       'content': '1, 5, 5, 5',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'},
     {'index': 2,
      'message': {'role': 'assistant',
       'content': '[1, 5, 5, 4]',
       'refusal': None},
      'logprobs': None,

In [ ]:
res_df = pd.DataFrame(results)
res_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         203 non-null    object
 1   custom_id  203 non-null    object
 2   response   203 non-null    object
 3   error      0 non-null      object
dtypes: object(4)
memory usage: 6.5+ KB

In [ ]:
def get_response(input_dict):
  return input_dict['body']['choices'][0]['message']['content'].split('Actionability:')[-1]

In [ ]:
res_df['gpt_res'] = res_df['response'].progress_apply(get_response)

100%|██████████| 203/203 [00:00<00:00, 61118.64it/s]

In [ ]:
res_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         203 non-null    object
 1   custom_id  203 non-null    object
 2   response   203 non-null    object
 3   error      0 non-null      object
 4   gpt_res    203 non-null    object
dtypes: object(5)
memory usage: 8.1+ KB

In [ ]:
res_df['gpt_res']=res_df['gpt_res'].apply(lambda x: x.replace('\x15',''))
res_df['gpt_res']

0      [1, 5,\nAndFeel good grief['VisualStyleBackCol...
1                                             4, 5, 3, 4
2      3, 5, ..ocrisy exist now\<)-> osloSuccessful p...
3                                           [1, 5, 4, 5]
4                                             1, 5, 5, 4
                             ...
198    [1, 5,.Gray_uppled_periods_dataset_ring.tsv_st...
199                   Evaluation Form:\n \n-[1, 4, 5, 5]
200                                         [1, 5, 5, 5]
201                                           2, 5, 5, 4
202                                           1, 4, 5, 5
Name: gpt_res, Length: 203, dtype: object

In [ ]:
res_df['index'] = res_df.custom_id.apply(lambda x: int(x.replace('task-','')))

In [ ]:
resu = res_df[['index', 'gpt_res']]
resu.to_excel('data/gpt4_gen_response_sample.xlsx', index=False)

#combining generated explanation response from gpt-4 with the data

In [ ]:
resu_exp=pd.read_excel('data/gpt4_gen_response_sample.xlsx')
resu_exp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   index    203 non-null    int64
 1   gpt_res  203 non-null    object
dtypes: int64(1), object(1)
memory usage: 3.3+ KB

In [ ]:
wrong_indices=[]
for i in range(len(resu_exp)):
  if len(resu_exp['gpt_res'][i].replace('[','').replace(']','').split(',')) != 4 and not resu_exp['gpt_res'][i].replace('[','').replace(']','').split(',')[-1].isdigit():
    wrong_indices.append(i)
len(wrong_indices), wrong_indices

(0, [])

In [ ]:
import time
for index in tqdm(wrong_indices):

  act_prompt_gen='''
You will be given a claim, some credible information called the evidence, a label that shows whether the claim is true or false, and four explanations for the label.

Your task is to evaluate each of the four explanations on one metric and give a score to each of the four explanations.

Please make sure you read and understand these instructions carefully. Please keep this document open while reviewing, and refer to it as needed.

Evaluation Criteria:

Actionability (1-5) - misinformation detection and factual correction backed up by credible sources. The explanation should provide an indication of which parts of the claim include misalignment with the evidence.In addition, the explanation should provide a corrected version of the erroneous claim.

Evaluation Steps:

1. Read the claim, evidence and the explanations carefully.
2. Compare the claim with the evidence and identify the errors or misalignment parts between the claim and the evidence.
3. Assess how well the explanations cover the errors detected, the credible sources provided, and the degree of error correction of the claim in each explanation.
4. Assign a score from 1 to 5 to the metric for each of the four explanations.
5. the output should be an array of scores/numbers only

Example:


Claim:

{}

Evidence:

{}

Label:

{}

source:

{}

Explanation1:

{}

Explanation2:

{}

Explanation3:

{}

Explanation4:

{}


Evaluation Form (scores ONLY):

[Actionability for explanation1, Actionability for explanation2, Actionability for explanation3, Actionability for explanation4]
'''.format(df.claim[index], df.evidence[index],	df.label[index], df.sources[index], df.explanation[index], df.mistral_exp[index], df.llama_exp[index],
           df['gpt-4_exp'][index])
  resu_exp.gpt_res[index]=get_categories(act_prompt_gen)
  time.sleep(1)

  0%|          | 0/12 [00:00<?, ?it/s]<ipython-input-79-8cc77b3e0433>:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resu_exp.gpt_res[index]=get_categories(act_prompt_gen)
  8%|▊         | 1/12 [00:03<00:40,  3.66s/it]<ipython-input-79-8cc77b3e0433>:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resu_exp.gpt_res[index]=get_categories(act_prompt_gen)
 17%|█▋        | 2/12 [00:06<00:33,  3.36s/it]<ipython-input-79-8cc77b3e0433>:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resu_exp.gpt_res[index]=get_categories(act_prompt_gen)
 25%|██▌       | 3/12 [00:08<00:25,  2.79s/it]<ipython-input-79-8cc77b3e0433>:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resu_exp.gpt_res[index]=get_categories(act_prompt_gen)
 33%|███▎      | 4/12 [00:11<00:21,  2.74s/it]<ipython-input-79-8cc77b3e0433>:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resu_exp.gpt_res[index]=get_categories(act_prompt_gen)
 42%|████▏     | 5/12 [00:14<00:19,  2.78s/it]<ipython-input-79-8cc77b3e0433>:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resu_exp.gpt_res[index]=get_categories(act_prompt_gen)
 50%|█████     | 6/12 [00:17<00:16,  2.82s/it]<ipython-input-79-8cc77b3e0433>:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resu_exp.gpt_res[index]=get_categories(act_prompt_gen)
 58%|█████▊    | 7/12 [00:20<00:14,  2.94s/it]<ipython-input-79-8cc77b3e0433>:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resu_exp.gpt_res[index]=get_categories(act_prompt_gen)
 67%|██████▋   | 8/12 [00:23<00:11,  2.94s/it]<ipython-input-79-8cc77b3e0433>:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resu_exp.gpt_res[index]=get_categories(act_prompt_gen)
 75%|███████▌  | 9/12 [00:26<00:08,  2.99s/it]<ipython-input-79-8cc77b3e0433>:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resu_exp.gpt_res[index]=get_categories(act_prompt_gen)
 83%|████████▎ | 10/12 [00:29<00:06,  3.12s/it]<ipython-input-79-8cc77b3e0433>:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resu_exp.gpt_res[index]=get_categories(act_prompt_gen)
 92%|█████████▏| 11/12 [00:32<00:02,  3.00s/it]<ipython-input-79-8cc77b3e0433>:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resu_exp.gpt_res[index]=get_categories(act_prompt_gen)
100%|██████████| 12/12 [00:35<00:00,  2.96s/it]

In [ ]:
resu_exp.tail()

     index       gpt_res
198    198  [1, 5, 5, 1]
199    199  [1, 4, 5, 5]
200    200  [1, 5, 5, 5]
201    201    2, 5, 5, 4
202    202    1, 4, 5, 5

In [ ]:
sorted_exp=[]
for i in range(len(resu_exp)):
  sorted_exp.append(resu_exp['gpt_res'][resu_exp.index==i][i])

In [ ]:
df['gpt-4_eval']=sorted_exp

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   claim                   203 non-null    object
 1   evidence                203 non-null    object
 2   sources                 87 non-null     object
 3   label                   203 non-null    bool
 4   metadata                203 non-null    object
 5   explanation             203 non-null    object
 6   Human_annotation_exp    203 non-null    object
 7   mistral_exp             203 non-null    object
 8   Human_annotation_exp.1  203 non-null    object
 9   llama_exp               203 non-null    object
 10  Human_annotation_exp.2  203 non-null    object
 11  gpt-4_exp               203 non-null    object
 12  Human_annotation_exp.3  203 non-null    object
 13  gpt-4_eval              203 non-null    object
dtypes: bool(1), object(13)
memory usage: 20.9+ KB

In [ ]:
df.to_excel('data/sample_data_fin_evals.xlsx', index=False)