In [1]:
# Make sure you have the latest version of the SDK available to use the Batch API
!pip install openai --upgrade

Requirement already satisfied: openai in /usr/local/lib/python3.10/dist-packages (1.59.4)
Collecting openai
  Downloading openai-1.59.6-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.10/dist-packages (from openai) (3.7.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.10/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from openai) (0.8.2)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from openai) (2.10.4)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.10/dist-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.10/dist-packages (from openai) (4.12.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai) (3.10)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai) (1.2.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->openai) (2024.12.14)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.14.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1.9.0->openai) (2.27.2)
Downloading openai-1.59.6-py3-none-any.whl (454 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 454.8/454.8 kB 7.1 MB/s eta 0:00:00
Installing collected packages: openai
  Attempting uninstall: openai
    Found existing installation: openai 1.59.4
    Uninstalling openai-1.59.4:
      Successfully uninstalled openai-1.59.4
Successfully installed openai-1.59.6

In [2]:
%cd /content/drive/MyDrive/second_paper_insha_allah

/content/drive/MyDrive/second_paper_insha_allah

In [3]:
import json
from openai import OpenAI
import pandas as pd
from tqdm import tqdm
from IPython.display import Image, display
tqdm.pandas()

In [4]:
client = OpenAI(api_key="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")

In [25]:
dataset_path = "data/total_data.xlsx"

df = pd.read_excel(dataset_path)
df.head()

,claim,evidence,sources,label,explanation,metadata,mistral_exp,llama_exp
0,Adrienne Bailon is an accountant.,Adrienne Eliza Houghton née Bailon ; born Oct...,NaN,False,Adrienne Bailon is an american singer-songwrit...,error_correction_only,"Based on the provided evidence, the claim that...","Based on the evidence, the claim ""Adrienne Bai..."
1,"Stranger Things is set in Bloomington, Indiana.","Set in the fictional town of Hawkins , Indiana...",NaN,False,"Stranger Things is set in Hawkins, Indiana.",error_correction_only,"Based on the provided evidence, the claim that...","Actionable Explanation:\n\nThe claim ""Stranger..."
2,Puerto Rico is not an unincorporated territory...,"Puerto Rico Spanish for `` Rich Port '' , of...",NaN,False,It is an unincorporated territory of the unite...,error_correction_only,"The claim that ""Puerto Rico is not an unincorp...",Actionable Explanation:\n\nThe claim that Puer...
3,Peggy Sue Got Married is a Egyptian film relea...,Peggy Sue Got Married is a 1986 American comed...,NaN,False,Peggy sue got married is a 1986 american comed...,error_correction_only,"The claim that ""Peggy Sue Got Married is a Egy...","Based on the provided evidence, the claim ""Peg..."
4,Andy Roddick lost 5 Master Series between 2002...,Roddick was ranked in the top 10 for nine cons...,NaN,False,Roddick lost the Master Series between 2002 an...,error_correction_only,"The claim that ""Andy Roddick lost 5 Master Ser...","Based on the evidence, the claim that Andy Rod..."

In [6]:
df=df[['claim',	'evidence',	'sources',	'label']]

#testing the prompt

In [7]:
act_prompt_gen='''
You will be given a claim, some credible information called the evidence, and a label that shows whether the claim is true or false.

Your task is to generate an actionable explanation for the label based on the evidence.

Please make sure you read and understand these instructions carefully. Please keep this document open while reviewing, and refer to it as needed.

Evaluation Criteria:

Actionability - misinformation detection and factual correction backed up by credible sources. The explanation should provide an indication of which parts of the claim include misalignment with the evidence.In addition, the explanation should provide a corrected version of the erroneous claim.

Evaluation Steps:

1. Read the claim, evidence and label carefully.
2. Compare the claim with the evidence and identify the errors or misalignment parts between the claim and the evidence.
3. Generate an actionable explanation that covers the errors detected and corrects the errors of the claim.
4. Restrict your knowledge to the evidence only.


Example:


Claim:

{}

Evidence:

{}

Label:

{}

Source:

{}

Evaluation Form:

- Actionability:
'''.format(df.claim[2], df.evidence[2],	df.sources[2],	df.label[2])

In [8]:
def get_categories(act_prompt_gen):
    response = client.chat.completions.create(
    model="gpt-4-1106-preview",
    temperature=0,
    messages=[
        {
            "role": "user",
            "content": act_prompt_gen
        }
    ],
    )

    return response.choices[0].message.content

In [18]:
get_categories(act_prompt_gen)

'- Actionability: The claim states that Puerto Rico is not an unincorporated territory of the United States, which is incorrect. The evidence clearly states that Puerto Rico is officially an unincorporated territory of the United States, located in the northeast Caribbean Sea. Therefore, the claim misaligns with the evidence provided.\n\nThe correct version of the claim should be: "Puerto Rico is an unincorporated territory of the United States."'

#creating the batch file

In [9]:
# Creating an array of json tasks

tasks = []

for index, row in df.iterrows():

    act_prompt_gen='''
You will be given a claim, some credible information called the evidence, a label that shows whether the claim is true or false, and an explanation for
the label.

Your task is to evaluate the explanation on one metric.

Please make sure you read and understand these instructions carefully. Please keep this document open while reviewing, and refer to it as needed.

Evaluation Criteria:

Actionability (1-5) - misinformation detection and factual correction backed up by credible sources. The explanation should provide an indication of which parts of the claim include misalignment with the evidence.In addition, the explanation should provide a corrected version of the erroneous claim.

Evaluation Steps:

1. Read the claim, evidence and the explanation carefully.
2. Compare the claim with the evidence and identify the errors or misalignment parts between the claim and the evidence.
3. Assess how well the explanation covers the errors detected and the degree of error correction of the claim in the explanation.
4. Assign a score from 1 to 5 to the metric.

Example:


Claim:

{}

Evidence:

{}

Label:

{}

Explanation:

{}

Evaluation Form (scores ONLY):

- Actionability:
'''.format(df.claim[index], df.evidence[index],	df.label[index], df.sources[index])


    task = {
        "custom_id": f"task-{index}",
        "method": "POST",
        "url": "/v1/chat/completions",
        "body": {
            # This is what you would have in your Chat Completions API call
            "model": "gpt-4-1106-preview",
            "temperature": 0,
            "messages": [
                {
                    "role": "user",
                    "content": act_prompt_gen
                }
            ],
        }
    }

    tasks.append(task)

In [11]:
tasks[100]

{'custom_id': 'task-100',
 'method': 'POST',
 'url': '/v1/chat/completions',
 'body': {'model': 'gpt-4-1106-preview',
  'temperature': 0,
  'messages': [{'role': 'user',
    'content': "\nYou will be given a claim, some credible information called the evidence, and a label that shows whether the claim is true or false.\n\nYour task is to generate an actionable explanation for the label based on the evidence.\n\nPlease make sure you read and understand these instructions carefully. Please keep this document open while reviewing, and refer to it as needed.\n\nEvaluation Criteria:\n\nActionability - misinformation detection and factual correction backed up by credible sources. The explanation should provide an indication of which parts of the claim include misalignment with the evidence.In addition, the explanation should provide a corrected version of the erroneous claim. \n\nEvaluation Steps:\n\n1. Read the claim, evidence and label carefully.\n2. Compare the claim with the evidence and identify the errors or misalignment parts between the claim and the evidence.\n3. Generate an actionable explanation that covers the errors detected and corrects the errors of the claim.\n4. Restrict your knowledge to the evidence only.\n\n\nExample:\n\n\nClaim:\n\nDoctor Who was written by the Ancient Greeks.\n\nEvidence:\n\nThe series is led by head writer and executive producer Steven Moffat , alongside executive producer Brian Minchin . It is the third and final series overseen by the two as executive producers , as well as Moffat 's sixth and final series as head writer .\n\nLabel:\n\nFalse\n\nSource:\n\nhttps://en.wikipedia.org/wiki/Doctor_Who_series_10\n\nEvaluation Form:\n\n- Actionability:\n"}]}}

In [27]:
#tasks=tasks[:5]

In [12]:
# Creating the file

file_name = "data/batch_claims.jsonl"

with open(file_name, 'w') as file:
    for obj in tasks:
        file.write(json.dumps(obj) + '\n')

#upload the batch file

In [13]:
batch_file = client.files.create(
  file=open(file_name, "rb"),
  purpose="batch"
)

In [14]:
print(batch_file)

FileObject(id='file-SQo3HjXMYnBYaKML1kgW5S', bytes=5310753, created_at=1736644767, filename='batch_claims.jsonl', object='file', purpose='batch', status='processed', status_details=None)

In [15]:
batch_file.id

'file-SQo3HjXMYnBYaKML1kgW5S'

#Creating the batch job

In [16]:
batch_job = client.batches.create(
  input_file_id='file-SQo3HjXMYnBYaKML1kgW5S',
  endpoint="/v1/chat/completions",
  completion_window="24h"
)

In [17]:
batch_job.id

'batch_678318bbce74819083feecf55679c938'

#check the status:

In [20]:
batch_job = client.batches.retrieve('batch_678318bbce74819083feecf55679c938')
print(batch_job)

Batch(id='batch_678318bbce74819083feecf55679c938', completion_window='24h', created_at=1736644796, endpoint='/v1/chat/completions', input_file_id='file-SQo3HjXMYnBYaKML1kgW5S', object='batch', status='completed', cancelled_at=None, cancelling_at=None, completed_at=1736645572, error_file_id=None, errors=None, expired_at=None, expires_at=1736731196, failed_at=None, finalizing_at=1736645483, in_progress_at=1736644797, metadata=None, output_file_id='file-YELLHGJBrJxg6tXDR3xm8U', request_counts=BatchRequestCounts(completed=1164, failed=0, total=1164))

In [21]:
batch_job.output_file_id

'file-YELLHGJBrJxg6tXDR3xm8U'

#Retrieving results

In [22]:
result_file_id = 'file-YELLHGJBrJxg6tXDR3xm8U'
result = client.files.content(result_file_id).content

In [23]:
result_file_name = "data/batch_job_results.jsonl"

with open(result_file_name, 'wb') as file:
    file.write(result)

In [24]:
# Loading data from saved file
results = []
with open(result_file_name, 'r') as file:
    for line in file:
        # Parsing the JSON string into a dict and appending to the list of results
        json_object = json.loads(line.strip())
        results.append(json_object)

In [25]:
results[1:100]

[{'id': 'batch_req_67831b6c527c8190be7b5b5c2ef45a40',
  'custom_id': 'task-1',
  'response': {'status_code': 200,
   'request_id': 'e9f4a22ea1b60c95cfcea577d18d1199',
   'body': {'id': 'chatcmpl-Aogx23uvnN3UYF2IUmbmWRl0ILTZf',
    'object': 'chat.completion',
    'created': 1736644868,
    'model': 'gpt-4-1106-preview',
    'choices': [{'index': 0,
      'message': {'role': 'assistant',
       'content': '- Actionability: The claim that "Stranger Things is set in Bloomington, Indiana" is false. The evidence clearly states that the show is set in the fictional town of Hawkins, Indiana, not Bloomington. To correct the claim: "Stranger Things is set in the fictional town of Hawkins, Indiana."',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'}],
    'usage': {'prompt_tokens': 303,
     'completion_tokens': 65,
     'total_tokens': 368,
     'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
     'completion_tokens_details': {'reasoning_tokens': 0,
      'audio_tokens': 0,
      'accepted_prediction_tokens': 0,
      'rejected_prediction_tokens': 0}},
    'service_tier': 'default',
    'system_fingerprint': None}},
  'error': None},
 {'id': 'batch_req_67831b6c63248190b36f7bce5e781eda',
  'custom_id': 'task-2',
  'response': {'status_code': 200,
   'request_id': 'de8dcfe2e4acb7c243a0d0f0b10f4330',
   'body': {'id': 'chatcmpl-Aogx5hh7UcYOZ8OVVa5tRSRP8zefG',
    'object': 'chat.completion',
    'created': 1736644871,
    'model': 'gpt-4-1106-preview',
    'choices': [{'index': 0,
      'message': {'role': 'assistant',
       'content': '- Actionability: The claim states that Puerto Rico is not an unincorporated territory of the United States, which is incorrect. The evidence clearly states that Puerto Rico is indeed an unincorporated territory of the United States, located in the northeast Caribbean Sea. The correct version of the claim should be: "Puerto Rico is an unincorporated territory of the United States."',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'}],
    'usage': {'prompt_tokens': 294,
     'completion_tokens': 80,
     'total_tokens': 374,
     'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
     'completion_tokens_details': {'reasoning_tokens': 0,
      'audio_tokens': 0,
      'accepted_prediction_tokens': 0,
      'rejected_prediction_tokens': 0}},
    'service_tier': 'default',
    'system_fingerprint': None}},
  'error': None},
 {'id': 'batch_req_67831b6c76fc8190af60ebd01116c0c9',
  'custom_id': 'task-3',
  'response': {'status_code': 200,
   'request_id': '55afc9b63d59a8c1f3c61a58cc37d068',
   'body': {'id': 'chatcmpl-Aogx8TzPsQvJakNu0jr8jo4w78Hyd',
    'object': 'chat.completion',
    'created': 1736644874,
    'model': 'gpt-4-1106-preview',
    'choices': [{'index': 0,
      'message': {'role': 'assistant',
       'content': '- Actionability: The claim states that "Peggy Sue Got Married" is an Egyptian film released in 1986. However, the evidence clearly indicates that "Peggy Sue Got Married" is an American comedy-drama film, not an Egyptian film. The evidence also confirms the release year as 1986, which aligns with the claim. Therefore, the error in the claim is the nationality of the film.\n\nThe corrected version of the claim should be: "Peggy Sue Got Married is a 1986 American comedy-drama film directed by Francis Ford Coppola."',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'}],
    'usage': {'prompt_tokens': 288,
     'completion_tokens': 121,
     'total_tokens': 409,
     'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
     'completion_tokens_details': {'reasoning_tokens': 0,
      'audio_tokens': 0,
      'accepted_prediction_tokens': 0,
      'rejected_prediction_tokens': 0}},
    'service_tier': 'default',
    'system_fingerprint': None}},
  'error': None},
 {'id': 'batch_req_67831b6c8ac4819090bfa25c1423e286',
  'custom_id': 'task-4',
  'response': {'status_code': 200,
   'request_id': 'cf72be693dd8c2e940510d2d352162be',
   'body': {'id': 'chatcmpl-AogxBRwELRG8hGdGtBD52beNO8GiN',
    'object': 'chat.completion',
    'created': 1736644877,
    'model': 'gpt-4-1106-preview',
    'choices': [{'index': 0,
      'message': {'role': 'assistant',
       'content': 'Actionability:\n\nThe claim states that Andy Roddick lost 5 Master Series between 2002 and 2010, which is not aligned with the evidence provided. The evidence clearly states that Roddick won five Masters Series in that period, not that he lost them. Therefore, the claim is false.\n\nThe corrected version of the claim should be: Andy Roddick won 5 Master Series between 2002 and 2010.',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'}],
    'usage': {'prompt_tokens': 273,
     'completion_tokens': 91,
     'total_tokens': 364,
     'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
     'completion_tokens_details': {'reasoning_tokens': 0,
      'audio_tokens': 0,
      'accepted_prediction_tokens': 0,
      'rejected_prediction_tokens': 0}},
    'service_tier': 'default',
    'system_fingerprint': None}},
  'error': None},
 {'id': 'batch_req_67831b6ca02481908fcc6d6a0cc776e6',
  'custom_id': 'task-5',
  'response': {'status_code': 200,
   'request_id': '6406388aefb3e19d7081c54f391f0619',
   'body': {'id': 'chatcmpl-AogxEEBDrOAdNQ4NeaX6z1gYb5doB',
    'object': 'chat.completion',
    'created': 1736644880,
    'model': 'gpt-4-1106-preview',
    'choices': [{'index': 0,
      'message': {'role': 'assistant',
       'content': '- Actionability: The claim states that Yoko Ono and John Lennon did not have two week-long Bed-Ins for Peace in 1969, which is directly contradicted by the evidence provided. The evidence clearly states that in 1969, during the Vietnam War, Yoko Ono and John Lennon indeed held two week-long Bed-Ins for Peace, one at the Hilton Hotel in Amsterdam and one at Fairmont The Queen Elizabeth in Montreal. These events were intended as non-violent protests against wars and as experimental tests of new ways to promote peace.\n\nThe corrected version of the claim should read: As the Vietnam War raged in 1969, Yoko Ono and her husband John Lennon held two week-long Bed-Ins for Peace, one at the Hilton Hotel in Amsterdam and one at Fairmont The Queen Elizabeth in Montreal.',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'}],
    'usage': {'prompt_tokens': 321,
     'completion_tokens': 172,
     'total_tokens': 493,
     'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
     'completion_tokens_details': {'reasoning_tokens': 0,
      'audio_tokens': 0,
      'accepted_prediction_tokens': 0,
      'rejected_prediction_tokens': 0}},
    'service_tier': 'default',
    'system_fingerprint': None}},
  'error': None},
 {'id': 'batch_req_67831b6cb68881908d59a16b706ed2b5',
  'custom_id': 'task-6',
  'response': {'status_code': 200,
   'request_id': 'a01573a388f50639c5fa55a7ab3ca197',
   'body': {'id': 'chatcmpl-AogxLMvltkDZb438Ypvza1uRfJJFq',
    'object': 'chat.completion',
    'created': 1736644887,
    'model': 'gpt-4-1106-preview',
    'choices': [{'index': 0,
      'message': {'role': 'assistant',
       'content': '- Actionability: The claim incorrectly identifies Grace Jones as a dancer. The evidence provided does not support this claim but instead lists her as a singer, songwriter, lyricist, supermodel, record producer, and actress. There is no mention of her being a dancer in the evidence provided. Therefore, the correct version of the claim should be: "Grace Jones is a Jamaican-born singer, songwriter, lyricist, supermodel, record producer, and actress."',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'}],
    'usage': {'prompt_tokens': 255,
     'completion_tokens': 94,
     'total_tokens': 349,
     'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
     'completion_tokens_details': {'reasoning_tokens': 0,
      'audio_tokens': 0,
      'accepted_prediction_tokens': 0,
      'rejected_prediction_tokens': 0}},
    'service_tier': 'default',
    'system_fingerprint': None}},
  'error': None},
 {'id': 'batch_req_67831b6cc5f08190bc4d2a8fad8a4130',
  'custom_id': 'task-7',
  'response': {'status_code': 200,
   'request_id': 'a7b4de812f6c1487e6c9e5fba315bf7f',
   'body': {'id': 'chatcmpl-AogxOKfOlM5zywO6c88y2V6DyM7ub',
    'object': 'chat.completion',
    'created': 1736644890,
    'model': 'gpt-4-1106-preview',
    'choices': [{'index': 0,
      'message': {'role': 'assistant',
       'content': 'Actionability:\n\nThe claim states that Willie Nelson dropped out of college after three years, which is not aligned with the evidence provided. The evidence clearly states that Nelson attended Baylor University for two years before dropping out, not three. Therefore, the claim is false.\n\nThe corrected version of the claim should read: Willie Nelson dropped out of college after two years, not three, because he was succeeding in music.',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'}],
    'usage': {'prompt_tokens': 249,
     'completion_tokens': 82,
     'total_tokens': 331,
     'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
     'completion_tokens_details': {'reasoning_tokens': 0,
      'audio_tokens': 0,
      'accepted_prediction_tokens': 0,
      'rejected_prediction_tokens': 0}},
    'service_tier': 'default',
    'system_fingerprint': None}},
  'error': None},
 {'id': 'batch_req_67831b6cd66c81909a687b20d0b560bb',
  'custom_id': 'task-8',
  'response': {'status_code': 200,
   'request_id': '70a4be19a1b2c956e832368ab6d071f0',
   'body': {'id': 'chatcmpl-AogxRmgGEcFLpxum8G948q0u2qDcv',
    'object': 'chat.completion',
    'created': 1736644893,
    'model': 'gpt-4-1106-preview',
    'choices': [{'index': 0,
      'message': {'role': 'assistant',
       'content': '- Actionability: The claim that "Furia is adapted from a short story by Anna Politkovskaya" is false. The evidence clearly states that "Furia is a 1999 French romantic drama film directed by Alexandre Aja, who co-wrote the screenplay with Grégory Levasseur, adapted from the science fiction short story \'Graffiti\' by Julio Cortázar." There is no mention of Anna Politkovskaya in the context of the film\'s source material. Therefore, the correct information is that "Furia" is adapted from the short story "Graffiti" by Julio Cortázar, not by Anna Politkovskaya.',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'}],
    'usage': {'prompt_tokens': 280,
     'completion_tokens': 139,
     'total_tokens': 419,
     'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
     'completion_tokens_details': {'reasoning_tokens': 0,
      'audio_tokens': 0,
      'accepted_prediction_tokens': 0,
      'rejected_prediction_tokens': 0}},
    'service_tier': 'default',
    'system_fingerprint': None}},
  'error': None},
 {'id': 'batch_req_67831b6ce5788190adfeb1fd8706ee46',
  'custom_id': 'task-9',
  'response': {'status_code': 200,
   'request_id': '92289b17777f80e797e608fd3d788a7d',
   'body': {'id': 'chatcmpl-AogxVZiNuMid4p0TW00GkGoDjQXc5',
    'object': 'chat.completion',
    'created': 1736644897,
    'model': 'gpt-4-1106-preview',
    'choices': [{'index': 0,
      'message': {'role': 'assistant',
       'content': "- Actionability: The claim that C. S. Forester's first name was Carl is false. The evidence clearly states that the full name of the individual known by the pen name C. S. Forester was Cecil Louis Troughton Smith. Therefore, the correct first name is Cecil, not Carl. The actionable explanation is to correct the claim by stating that C. S. Forester's first name was Cecil, as evidenced by the provided information about his full name and pen name.",
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'}],
    'usage': {'prompt_tokens': 305,
     'completion_tokens': 101,
     'total_tokens': 406,
     'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
     'completion_tokens_details': {'reasoning_tokens': 0,
      'audio_tokens': 0,
      'accepted_prediction_tokens': 0,
      'rejected_prediction_tokens': 0}},
    'service_tier': 'default',
    'system_fingerprint': None}},
  'error': None},
 {'id': 'batch_req_67831b6cf9148190b9b011537ed24831',
  'custom_id': 'task-10',
  'response': {'status_code': 200,
   'request_id': '5ecaf13e6b3121923814b4404ea8be0c',
   'body': {'id': 'chatcmpl-AogxYPXCLWM85KhpfJ15aa24G5bvd',
    'object': 'chat.completion',
    'created': 1736644900,
    'model': 'gpt-4-1106-preview',
    'choices': [{'index': 0,
      'message': {'role': 'assistant',
       'content': '- Actionability: The claim states that "Kong: Skull Island" is a book, which is incorrect. The evidence clearly indicates that "Kong: Skull Island" is a 2017 American action-adventure monster film directed by Jordan Vogt-Roberts. The claim misaligns with the evidence as it incorrectly categorizes the nature of "Kong: Skull Island." The corrected version of the claim should state: "Kong: Skull Island is a 2017 American action-adventure monster film."',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'}],
    'usage': {'prompt_tokens': 274,
     'completion_tokens': 106,
     'total_tokens': 380,
     'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
     'completion_tokens_details': {'reasoning_tokens': 0,
      'audio_tokens': 0,
      'accepted_prediction_tokens': 0,
      'rejected_prediction_tokens': 0}},
    'service_tier': 'default',
    'system_fingerprint': None}},
  'error': None},
 {'id': 'batch_req_67831b6d0910819099795b6e5535ec9e',
  'custom_id': 'task-11',
  'response': {'status_code': 200,
   'request_id': '2020b978de7570e47c1f3091271a9008',
   'body': {'id': 'chatcmpl-AogxbIIXzOwOpSG5rbLG1z4xbkskQ',
    'object': 'chat.completion',
    'created': 1736644903,
    'model': 'gpt-4-1106-preview',
    'choices': [{'index': 0,
      'message': {'role': 'assistant',
       'content': '- Actionability: The claim states that "The Challenge" was a scripted show. However, the evidence provided clearly indicates that "The Challenge," originally known as "Road Rules: All Stars" and later "Real World/Road Rules Challenge," is a reality game show that was spun off from MTV\'s reality shows "Real World" and "Road Rules." Reality game shows typically feature unscripted interactions among participants as they compete in various challenges, which contradicts the claim that "The Challenge" was scripted. Therefore, the correct information is that "The Challenge" is a reality game show, not a scripted show, as the claim incorrectly suggests.',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'}],
    'usage': {'prompt_tokens': 271,
     'completion_tokens': 132,
     'total_tokens': 403,
     'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
     'completion_tokens_details': {'reasoning_tokens': 0,
      'audio_tokens': 0,
      'accepted_prediction_tokens': 0,
      'rejected_prediction_tokens': 0}},
    'service_tier': 'default',
    'system_fingerprint': None}},
  'error': None},
 {'id': 'batch_req_67831b6d1d5c8190b1daa7a7fc7f59d9',
  'custom_id': 'task-12',
  'response': {'status_code': 200,
   'request_id': '7dd34871e57aec5b979ebbc1a0ab0619',
   'body': {'id': 'chatcmpl-AogxfNSZDnJXDqxB457SlqYrpUdP8',
    'object': 'chat.completion',
    'created': 1736644907,
    'model': 'gpt-4-1106-preview',
    'choices': [{'index': 0,
      'message': {'role': 'assistant',
       'content': '- Actionability: The claim states that "Red Headed Stranger" is a movie, which is incorrect based on the evidence provided. The evidence clearly indicates that "Red Headed Stranger" is a 1975 album by Willie Nelson, which is a concept album about a fugitive. There is no mention in the evidence of "Red Headed Stranger" being a movie. Therefore, the correct information is that "Red Headed Stranger" is an album, not a movie. The actionable explanation is to inform that the claim misidentifies the nature of "Red Headed Stranger," and the corrected version of the claim should state: "Red Headed Stranger is a 1975 album by American outlaw country singer Willie Nelson."',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'}],
    'usage': {'prompt_tokens': 270,
     'completion_tokens': 148,
     'total_tokens': 418,
     'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
     'completion_tokens_details': {'reasoning_tokens': 0,
      'audio_tokens': 0,
      'accepted_prediction_tokens': 0,
      'rejected_prediction_tokens': 0}},
    'service_tier': 'default',
    'system_fingerprint': None}},
  'error': None},
 {'id': 'batch_req_67831b6d362c8190b03b63c77beeb1ad',
  'custom_id': 'task-13',
  'response': {'status_code': 200,
   'request_id': 'f7d0941cddd04ee9c3e9bdc10bead3ef',
   'body': {'id': 'chatcmpl-Aogxja9oIKVNOAz0BMqr5tRU5K2yB',
    'object': 'chat.completion',
    'created': 1736644911,
    'model': 'gpt-4-1106-preview',
    'choices': [{'index': 0,
      'message': {'role': 'assistant',
       'content': 'The claim that Chester Bennington is not a singer is false. The evidence clearly states that Chester Charles Bennington was an American musician, singer, songwriter, and actor. He is best known as the lead vocalist of rock bands such as Linkin Park, Dead by Sunrise, and the live rock cover band Bucket of Weenies. Additionally, he served as the lead vocalist for Stone Temple Pilots from 2013 to 2015. His role as a vocalist was particularly highlighted with Linkin Park\'s debut album, Hybrid Theory, in 2000, which achieved massive commercial success.\n\nThe misalignment in the claim is the assertion that Chester Bennington is not a singer, which is directly contradicted by the evidence that confirms his role as a lead vocalist for several well-known rock bands. The corrected version of the claim should acknowledge Chester Bennington\'s established career as a singer: "Chester Bennington was an American musician, singer, songwriter, and actor, best known as the lead vocalist of rock bands Linkin Park, Dead by Sunrise, and others."',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'}],
    'usage': {'prompt_tokens': 352,
     'completion_tokens': 221,
     'total_tokens': 573,
     'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
     'completion_tokens_details': {'reasoning_tokens': 0,
      'audio_tokens': 0,
      'accepted_prediction_tokens': 0,
      'rejected_prediction_tokens': 0}},
    'service_tier': 'default',
    'system_fingerprint': None}},
  'error': None},
 {'id': 'batch_req_67831b6d55c081909102c2e4bf2342e4',
  'custom_id': 'task-14',
  'response': {'status_code': 200,
   'request_id': '8a9bfa5758a5508867d7c7027e9b205b',
   'body': {'id': 'chatcmpl-AogxpyGQhBp4kwKhLIpFw2ljtAEMs',
    'object': 'chat.completion',
    'created': 1736644917,
    'model': 'gpt-4-1106-preview',
    'choices': [{'index': 0,
      'message': {'role': 'assistant',
       'content': '- Actionability: The claim that David Beckham has zero middle names is false. The evidence clearly states that his full name is "David Robert Joseph Beckham," indicating that he has two middle names: Robert and Joseph. The corrected version of the claim should be: "David Beckham has two middle names, Robert and Joseph."',
       'refusal': None},
      'logprobs': None,
      'finish_reason': 'stop'}],
    'usage': {'prompt_tokens': 263,
     'completion_tokens': 65,
     'total_tokens': 328,
     'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
     'completion_tokens_details': {'reasoning_tokens': 0,
      'audio_tokens': 0,
      'accepted_prediction_tokens': 0,
      'rejected_prediction_tokens': 0}},
    'service_tier': 'default',

In [26]:
res_df = pd.DataFrame(results)
res_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1164 entries, 0 to 1163
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         1164 non-null   object
 1   custom_id  1164 non-null   object
 2   response   1164 non-null   object
 3   error      0 non-null      object
dtypes: object(4)
memory usage: 36.5+ KB

In [43]:
def get_response(input_dict):
  return input_dict['body']['choices'][0]['message']['content'].split('Actionability:')[-1]

In [44]:
res_df['gpt_res'] = res_df['response'].progress_apply(get_response)

100%|██████████| 1164/1164 [00:00<00:00, 125845.34it/s]

In [49]:
res_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1164 entries, 0 to 1163
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         1164 non-null   object
 1   custom_id  1164 non-null   object
 2   response   1164 non-null   object
 3   error      0 non-null      object
 4   gpt_res    1164 non-null   object
 5   index      1164 non-null   int64
dtypes: int64(1), object(5)
memory usage: 54.7+ KB

In [46]:
res_df['gpt_res'][7]

'\n\nThe claim states that Willie Nelson dropped out of college after three years, which is not aligned with the evidence provided. The evidence clearly states that Nelson attended Baylor University for two years before dropping out, not three. Therefore, the claim is false.\n\nThe corrected version of the claim should read: Willie Nelson dropped out of college after two years, not three, because he was succeeding in music.'

In [48]:
res_df['index'] = res_df.custom_id.apply(lambda x: int(x.replace('task-','')))

In [50]:
resu = res_df[['index', 'gpt_res']]
resu.to_excel('data/gpt4_gen_response.xlsx', index=False)

#combining generated explanation response from gpt-4 with the data

In [5]:
resu_exp=pd.read_excel('data/gpt4_gen_response.xlsx')
resu_exp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1164 entries, 0 to 1163
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   index    1164 non-null   int64
 1   gpt_res  1164 non-null   object
dtypes: int64(1), object(1)
memory usage: 18.3+ KB

In [18]:
resu_exp.tail()

      index                                            gpt_res
1159   1159  The claim that the U.S. Department of Justice ...
1160   1160  The claim that entering the wrong PIN into a c...
1161   1161  The claim that a 12-year-old Wisconsin girl di...
1162   1162  The claim that health officials announced in J...
1163   1163  The claim that police found 218 embalmed human...

In [16]:
sorted_exp=[]
for i in range(len(resu_exp)):
  sorted_exp.append(resu_exp['gpt_res'][resu_exp.index==i][i])

In [26]:
df['gpt-4_exp']=sorted_exp

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1164 entries, 0 to 1163
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   claim        1164 non-null   object
 1   evidence     1164 non-null   object
 2   sources      580 non-null    object
 3   label        1164 non-null   bool
 4   explanation  1164 non-null   object
 5   metadata     1164 non-null   object
 6   mistral_exp  1164 non-null   object
 7   llama_exp    1164 non-null   object
 8   gpt-4_exp    1164 non-null   object
dtypes: bool(1), object(8)
memory usage: 74.0+ KB

In [28]:
df.to_excel('data/total_data_fin_exp.xlsx', index=False)